### ISSUE TITLE
Seção Notícias

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#10]
Na listagem da 4a coluna, na seção de notícias, mostrar a imagem que estiver na chamada para ficar parecido com:

http://www.envolverde.com.br/

Como a imagem está definida dentro do HTML, será que dá pra fazer?

**Comment by leonardocsantoss** [comment]
Resolvido.
Ficou legal: http://teste.raiz.org.br/home/

**Comment by josircg** [comment]
1) Colocar a 4a coluna também na listagem dos artigos da seção.

2) Diminuir a altura do item de cada elemento. Tá muito largo.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
A seção de redes sociais deve ficar na horizontal e não na vertical.

**Comment by leonardocsantoss** [comment]
Ajustado.
