### ISSUE TITLE
Inclusão em lote de emails

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#100]
Novo PowerButton "Inclusão em Lote" na tela de Visitantes:

1. Abrir tela para receber um arquivo texto que conterá uma lista com emails. Colocar um help_text para lembrar o formato: email, nome da pessoa, telefone

2. Para cada email recebido: veificar primeiro se é de algum colaborador. Se não for, incluir em uma lista. 

3. Se o registro tiver nome e o email já não estiver na lista de visitante, incluir a pessoa como visitante. Se não tiver nome, não incluir. Atualizar o telefone se houver.

4. Ao final, mostrar a lista de emails "Emails de quem não é colaborador" e também o número de pessoas incluídas como visitante.

**Comment by leonardocsantoss** [comment]
Resolvido. Lembrando que acrescentei o uf no .csv, pois este campo é obrigatório na Pessoa.

**Comment by josircg** [comment]
Pode colocar em produção!

**Comment by leonardocsantoss** [comment]
Em produção.
