### ISSUE TITLE
Desabilitar Debug e implementar páginas de erro 400 e 500

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#102]
No ambiente de teste da Raiz, retire o debug para que a gente comece a receber as mensagens de erro. Temos que construir uma página bonitinha do erro 400/401/500 sempre dentro do template do site ao invés de mostrar a tela do admin.

**Comment by leonardocsantoss** [comment]
Resolvido. Ex.: http://teste.raiz.org.br/dasda
