### ISSUE TITLE
Montar o site teste2.raiz.org.br

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#106]
Aplicar o layout do site teste2.raiz.org.br no ambiente teste.raiz.org.br

**Comment by leonardocsantoss** [comment]
Para fazer aqueles texto do slideshow eu preciso das seguintes informações: data-x, data-y, data-start, texto, link. Isso para cada texto de cada slide.

**Comment by leonardocsantoss** [comment]
Já coloquei no ambiente de testes.

**Comment by josircg** [comment]
A listagem tem que ser melhorada. 

http://teste.raiz.org.br/section/documentos-oficiais/

Vamos montar uma embaixo da outra com as últimas notícias do lado direito.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
1) Ainda tá muito feio Leonardo. Os elementos tem que ficar mais destacados. Talvez colocar um quadro em volta de cada um dos elementos.

**Comment by leonardocsantoss** [comment]
Olha se ficou melhor assim. Coloquei um bg intercalando os elementos da listagem.

**Comment by josircg** [comment]
AInda não está legal. Não dá só para colocar uma borda ? 
Outra opção é que ao invés de mostrar o header, vamos mostrar apenas o título.

**Comment by leonardocsantoss** [comment]
Coloquei só a borda e retirei o header.

**Comment by josircg** [comment]
1) Colocar o link para o admin com o título "Sistema Integrado" ao lado da "Teia Digital".

2) No fórum, remover a seção das redes sociais.

3) Implementar a nuvem de tags

Os itens (1) e (2) pode colocar direto em produção.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei os itens 1 e 2 em produção.
