### ISSUE TITLE
Meus Grupos e Meus Tópicos 

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#107]
1) Temos que inverter a ordem do home da entrada do fórum: a primeira view tem que ser o Recentes e não mais os "Meus Grupos".

2) Controle de Participação dos Meus Grupos:

Na view que lista o Grupo, temos que ter uma estrela com fundo branco ou amarelo (igual no Loomio) ao lado do "Adicionar Novo Tópico"

http://teste.raiz.org.br/forum/grupo/4/

Caso a pessoa não faça parte do grupo, o fundo tem que ser branco e caso o usuário clique nela, ele passa a participar do grupo e a estrela passa a ter cor amarela.

Caso a estrela seja amarela e o usuário clique sobre ela, ele deixa de participar do grupo.

3) Temos que ter a mesma lógica para os tópicos. Tópicos marcados com estrela são os tiverem TopicoOuvinte.notificacao = 'P' (Prioritário)

4) Na view dos Recentes, temos que mostrar primeiro os prioritários e só depois os + recentes.

5) Na listagem dos tópicos também mostrar com estrela os tópicos prioritários

**Comment by leonardocsantoss** [comment]
1) Resolvido

2) Resolvido. Ficou estranha ela na cor amarela, então deixei o padrão do link, azul e quando passa o mouse em cima fica verde.
2.1) Se o usuário faz parte do grupo, ao clicar nela é chamada uma view que remove o GrupoUsuario.
2.2) Se o usuário não faz parte do grupo, ao clicar nela é chamada a view de solicitação de participação, caso o grupo seja público é criado automaticamente o GrupoUsuario, caso contrário, é enviado um email para os admins do grupo solicitando a entrada do usuário no grupo.

3) Resolvido. Neste caso é 'I' = 'Sempre receber notificações'

4) Resolvido

5) Resolvido.

**Comment by josircg** [comment]
1) O /forum tem que direcionar para o Recentes

2) Temos que ter um tooltip para indicar para o usuário "Marcar como Prioritário". 

A estrela tá MUITO feia :)) Tente usar a mesma do Loomio e pode colocar amarelo pois tem que chamar a atenção mesmo.

2.1. No caso do grupo "Participar do grupo" 

3) Temos que diferenciar o que é "Prioritário" do que é "Sempre receber notificações". Temos que ter uma nova opção.

6) Vamos colocar o editar membro e adicionar membro dentro da tela de edição do grupo. Do jeito que está, tá muito feio...

http://teste.raiz.org.br/forum/grupo/1/

7) O Categoria tem que vir antes do Adicionar Tópico.

**Comment by leonardocsantoss** [comment]
Ajustado.
