### ISSUE TITLE
Erro no cadastro de um círculo

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#108]
NoReverseMatch at /admin/cadastro/circulo/add/

Reverse for 'cadastro_circulo_change' with arguments '('',)' and keyword arguments '{}' not found.
Request Method:	GET
Request URL:	http://www.raiz.org.br/admin/cadastro/circulo/add/
Django Version:	1.4.22
Exception Type:	NoReverseMatch
Exception Value:	
Reverse for 'cadastro_circulo_change' with arguments '('',)' and keyword arguments '{}' not found.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei direto em produção.
