### ISSUE TITLE
Coligações

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#109]
1) Tem que remover o número do membro do inline

http://www.raiz.org.br/admin/cadastro/coligacao/3/

Fazer o mesmo para a tela de articuladores

2) Temos que habilitar uma view igual a dos círculos onde a pessoa escolhe a UF e o sistema retorne as coligações daquele estado. Não precisa especificar a cidade.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes: http://teste.raiz.org.br/coligacoes/

**Comment by josircg** [comment]
Tem que listar também os candidatos a prefeito/vereador

**Comment by leonardocsantoss** [comment]
Ajustado.

**Comment by leonardocsantoss** [comment]
Em produção: http://www.raiz.org.br/coligacoes/

**Comment by josircg** [comment]
Durante a inclusão de um candidato na tela de coligações, existe uma opção para se escolher o membro.

Entretanto quando a pessoa é do perfil Coord.Política e também administrador do círculo, a tela de busca de membros está fazendo o filtro pelo estado da pessoa, ou seja, não está mostrando todos os membros.

Vc pode fazer o teste com o usuário abaixo:
http://www.raiz.org.br/admin/auth/user/981/

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei direto em produção.

**Comment by josircg** [comment]
Alterar o combobox para permitir visualizar TODAS as candidaturas. Remover também do combobox a opção "Fora do Brasil"

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei direto em produção.
