### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#11]
Copiar a definição e os arquivos que definem o favicon em:

https://github.com/josircg/raizcidadanista/tree/master/cadastro/static/site/icon

e colocar no novo site.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
Não está aparecendo na página principal.

**Comment by leonardocsantoss** [comment]
Esqueci de avisar. Coloquei apenas no ambiente de testes.
