### ISSUE TITLE
Visualização do tópico no celular

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#110]
Organizar a visualização das divs para a visualização no smartphone.

http://teste.raiz.org.br/forum/recentes/

* O menu não está colapsando
* A lista de tópicos tem que ser a primeira a aparecer.
* repare que a margem está enorme

http://teste.raiz.org.br/forum/grupo/2/topico/4/

* idem para a visualização do tópico
* idem para a margem

**Comment by leonardocsantoss** [comment]
A unica forma que encontre de fazer os tópicos aparecerem primeiro foi desabilitar o box de redes sociais e o box de eventos quando acessado pelo mobile.

**Comment by josircg** [comment]
* O tamanho do título está muito grande
* As margens laterais ainda estão MUITO MUITO grandes. Não dá para colocar apenas 2px ?

**Comment by leonardocsantoss** [comment]
2px é pouco demais. Reduzi para 5px.

**Comment by josircg** [comment]
O logo ainda não está legal. Veja como aparece na imagem. Tem que diminuir muito esse header para que o usuário ganhe espaço para visualizar as mensagens.
![screenshot_20160901-145343](https://cloud.githubusercontent.com/assets/634507/18178288/1ee54f3c-7054-11e6-813e-e197f796b0b9.png)

**Comment by leonardocsantoss** [comment]
Ajustado.
