### ISSUE TITLE
Melhoria na visualização dos círculos

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#111]
1) Incluir o texto do status quando este não estiver Ativo embaixo do nome do círculo com a mesma cor "grená" do logo da Raiz.

2) Quando tem mais de um jardineiro, ele fica grudado na linha anterior. Faz o teste com MG por exemplo.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Esse pode colocar direto em produção.

**Comment by leonardocsantoss** [comment]
Em produção.
