### ISSUE TITLE
Implantar o Personificar

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#112]

**Comment by leonardocsantoss** [comment]
Já tinha, só que só quem podia personificar era o usperuser. Coloquei para qualquer um que tenha acesso a tela de edição do user poder personificar.

Ps.: Está apenas no ambiente de testes.

**Comment by josircg** [comment]
Era para deixar apenas para superuser mesmo. Mas não estava funcionando em produção.

**Comment by leonardocsantoss** [comment]
O poweradmin que não estava pegando. Já fiz os ajustes em produção.
