### ISSUE TITLE
Incluir Action que totalize as receitas por UF/cidade

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#113]
Novo action na tela da Receita "Totalização por UF/cidade" que mostre um relatório (não precisa ser PDF) listando a totalização de receitas por cidade, totalizando por UF. A ordenação deve ser por UF + Cidade. Exemplo:

Estado / Cidade (Eleitoral ou Residencial caso eleitoral não esteja preenchida) / No contribuições / Arrecadado / Média
SP / São Paulo / 33  / 20.500,00 / 612,23
SP / São Carlos / 11 / 10.200,00
Total SP / 44 / 30.700,00

RJ / Rio de Janeiro...
etc.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
1) A média está errada
2) Incluir um Total Geral

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei direto em produção.
