### ISSUE TITLE
Erro ao gerar o pagamento a partir da despesa

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#114]
Ao clicar no Pagamento Integral e depois dar o salvar, o sistema retorna erro:

(1406, "Data too long for column 'referencia' at row 1")
Request Method: POST
Request URL:    http://www.raiz.org.br/admin/financeiro/despesa/1/
Django Version: 1.4.22
Exception Type: DatabaseError
Exception Value:  
(1406, "Data too long for column 'referencia' at row 1")

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei direto em produção.

**Comment by josircg** [comment]
O Tipo de Despesa não está sendo copiado para o Pagamento gerado.
http://www.raiz.org.br/admin/financeiro/despesa/3/

**Comment by leonardocsantoss** [comment]
1) Ajustado.
2) Adicionei.

Coloquei direto em produção.

**Comment by josircg** [comment]
NameError at /admin/financeiro/despesa/add/

http://www.raiz.org.br/admin/financeiro/despesa/8/

Quando eu tento marcar pagamento integral, dá erro

global name 'tipo_despesa' is not defined
Request Method:	POST
Request URL:	http://www.raiz.org.br/admin/financeiro/despesa/add/
global name 'tipo_despesa' is not defined

**Comment by leonardocsantoss** [comment]
Resolvido.
