### ISSUE TITLE
Erros aleatórios no formulário de colaborador

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#116]
Vamos retirar o captcha já que a pessoa tem que preencher o CPF corretamente.

Além disso, o email com o log de erro de cadastro tem que listar todos os campos do formulário senão eu não vou conseguir entrar em contato com a pessoa caso o formulário esteja errado.

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei direto em produção.
