### ISSUE TITLE
Incluir o contador no menu lateral "Não Lidos"

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#118]
No menu lateral esquerdo, incluir o número de mensagens não lidas dos grupos no qual o usuário ativo está inscrito:

http://www.raiz.org.br/forum/recentes/

Se o número for (0) não mostrar nada tanto para esse novo contador quanto para o contador de mensagens não lidas dos tópicos individuais que aparecem nas listagens dos tópicos como em:

http://www.raiz.org.br/forum/grupo/3/

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
A contagem está errada. Faça o login com (josir) nesse instante:
http://www.raiz.org.br/forum/

Tem 11 Recentes. Só que se eu clico nele, o sistema só mostra 5.

E não aparece nada no Não Lidos! Quando temos 5 mensagens.

**Comment by leonardocsantoss** [comment]
Precisamos mudar essa lógica, pois está muito confusa. Atualmente em "Recentes" aparece o número de "conversas não lidas". Minhas sugestões:

1. Retirar o contador de "conversas não lidas" do menu "Recentes";
2. Adicionar o contador de "**Tópicos** não lidos" no menu "Não lidas";
3. Mudar a view do "Não lidas" para mostrar os tópicos não lidos, hoje mostramos os grupos não lidos.

**Comment by josircg** [comment]
Leonardo, provavelmente teve alguma falha na comunicação pois o contador de conversas não lidas NÃO deveria aparecer no menu Recentes. Assim (1) e (2) era para ser sempre dessa forma.

O item (3) tem que mostrar os grupos mas a soma dos contadores de cada grupo tem que bater com o número indicado no contador, correto?

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei direto em produção.
