### ISSUE TITLE
Recadastramento de Filiados

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#120]
Hoje temos a rotina de envio de recadastramento que é chamada via:

http://teste.raiz.org.br/atualizar-cadastro/4-473-9a698969119d315e2c52/

1) Vamos refazer essa view para mostrar o mesmo formulário do Meu Perfil mas com 3 botões:

[Confirmar a minha participação]
[Quero ser apenas colaborador(a)] 
[Não quero mais fazer parte da Raiz]

Ao entrar na tela, já gravar um log "[RECAD] Usuário respondeu ao recadastramento"

2) Confirmar minha pré-filiação: criar novo atributo

Membro.confirmado = models.BooleanField(u'Recadastramento', default=False)

Se o usuário clicar no primeiro botão, marcar como confirmado e gerar um log "[RECAD] Usuário confirmou o cadastro como pré-filiado com o IP xxxxx"

4) Me tornar apenas colaborador: 

Marcar filiado=False
Log="[RECAD] Usuário passou a ser colaborador"

5) Não quero mais fazer parte da Raiz.

* Alterar o status_email para cancelado
* Log="[RECAD] Usuário pediu desligamento"

6) Caso o hash tenha perdido a validade, temos que dar uma mensagem inteligível para pessoa.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
1) Tem que agrupar os dados na mesma linha. Endereço, por exemplo tem que ter Cidade, UF tudo na mesma linha. Telefone idem. CPF, RG, Sexo e Estado Civil idem.
2) Troque o texto de Filiado para "Pré-filiado"
3) No caso de filiado, tem que incluir os dados do TSE
4) Os botões de confirmação estão muito tênues, tem que ser verdes e com borda.

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
1) Juntar Endereço, No, Complemento, Cidade, UF e CEP tudo em uma mesma string com o label: Residência

2) Colocar UF + Cidade Eleitoral + Zona + Seção + Título em uma mesma linha

3) Se o cara já tiver feito o recadastramento, tem que aparecer a mensagem "Recadastramento já foi efetuado"

4) Trocar mensagem final "Você pediu desligamento da RAiZ" por "Desligamento efetuado com sucesso"

**Comment by leonardocsantoss** [comment]
Ajustado.

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
6. Novo atributo Membro.status: (A,C), default=Ativo. Caso status_email = Cancelado, marcar Membro.status = Cancelado.

No caso do botão "Não quero mais fazer parte da Raiz": setar também confirmado =True, filiado = False, status='C'

7. Remover o botão "Atualizar dados" e as seções "Meus Círculos" e "Minhas contribuições"

Caso a pessoa confirme sua participação, fazer o login automático do usuário, mostrar uma nova tela: 

* com os círculos aos quais ele pertence;
* caso você faça parte de algum círculo que não esteja listado aqui, <<peça o registro do seu círculo>> e direcionar para a tela de recadastramento;
* frame http://teste.raiz.org.br/circulos/ para que ele se cadastre em um círculo existente;

8. Alterar a view do /circulo para que ele possa buscar também os círculos temáticos em uma mesma tela.

**Comment by leonardocsantoss** [comment]
7. Todos esses dados temos na tela "Meu Perfil". Seria mais interessante redirecionar o usuário para essa tela?

8. Juntei as duas telas em uma só. Veja em: http://teste.raiz.org.br/circulos/

9. Mandei uma message e já redirecionei o usuário para a tela de "Meu Perfil".

Ps.: Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Leonardo, ficou ruim trazer o "Meu Perfil". Você tem sempre que pensar que o usuário não é de informática, TEM MUITO POUCA INTIMIDADE com sites assim a tela não pode ter muitas opções pois a pessoa SE PERDE.

Assim, tente fazer exatamente como eu estou colocando:

7.0) Já fazer o login automático dele;

7.1) Mostrar o texto "Segue a relação dos círculos aos quais você faz parte:"
listar os círculos aos quais ele pertence (não repita o mesmo layout - só mostre o nome do círculo.

7.2) frame http://teste.raiz.org.br/circulos/ para que ele possa se cadastrar em um círculo existente;

7.3) caso você faça parte de algum círculo que não esteja listado aqui, <<peça o registro do seu círculo>> e direcionar para a tela de recadastramento;

7.4) Caso você queira alterar os seus dados pessoais, <ir para a tela de edição>

8) A tela tem que ter uma busca única sem já trazer todos os círculos identitários. 

9) Acesse: http://teste.raiz.org.br/recadastramento/16r-4hf-ccf4be5e3607ef7fed7d

Ele já fez o recadastramento. A mensagem está correta mas o sistema tem que seguir os mesmos passos que (7) para dar oportunidade dele se inscrever nos círculos.

**Comment by leonardocsantoss** [comment]
Resolvido. Está apenas no ambiente de testes.

**Comment by josircg** [comment]
8) Eu entrei como "juventude" e ele não trouxe nada. Acho melhor voltar atrás e listar todos pois as pessoas não saberão quais existem.

9) A tela de edição tá MUITO feia!!! Tem que melhorar muito ela.

http://teste.raiz.org.br/atualizar-cadastro/16r-4hg-03ca5e787baa8c7bba95?filiado=true

**Comment by leonardocsantoss** [comment]
8. Voltei ao código que listas todos os Círculos temáticos.
9. Ajustado.

**Comment by josircg** [comment]
http://www.raiz.org.br/recadastramento/2-4hl-87bde2d7672ba268bd50

1. A relação dos círculos que tem que ficar alinhadas com o título
2. Logo após a relação dos círculos tem que mostrar o texto "Caso queira se registrar em mais algum círculo, selecione a cidade ou o {{círculo temático}} com um link. Caso o usuário selecione o círculo temático, alternar o frame.

**Comment by leonardocsantoss** [comment]
1. Resolvido.
2. Cancelado!

Em produção.

**Comment by josircg** [comment]
Na tela do /meu-perfil caso o atributo do confirmado=False, abrir um diálogo:

"Estamos realizando o recadastramento da Raiz! Pedimos que responda:

<<Confirmo minha participação>> <<Não quero mais fazer parte da Raiz>>"

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei direto em produção.

**Comment by josircg** [comment]
1) Criar novo status=Inativo para o colaborador

2) Alterar o status de todos os colaboradores que confirmado=False para Status=Inativo

3) No login, caso o status=Inativo, levar o usuário para o meu perfil, mostrar a mensagem

"Seu cadastro está desativado pois você não respondeu ao recadastramento. Você quer voltar a fazer parte da Raiz ? 

E seguir a mesma lógica do Confirmado=False mostrando os 2 botões.

<<Confirmo minha participação na Raiz>> <<Não quero mais fazer parte da Raiz>>

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

Em vez de alterar a tela de Perfil, eu chamei a tela de recadastramento.

**Comment by josircg** [comment]
O script que vc rodou foi o abaixo?

Membro.objects.filter(confirmado=False).update(Status='I')

**Comment by leonardocsantoss** [comment]
É esse mesmo. Rodei no ambiente de testes.

**Comment by josircg** [comment]
Eu esqueci de rodar rodar o exclude(status='C')....
Vamos ter que baixar o backup mais recente e verificar quais estavam com 'C'....

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei direto em produção.
