### ISSUE TITLE
Inclusão e Edição do Tópico

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#121]
1) O botão de adicionar o tópico tem que ter um espaço BEM maior.

http://www.raiz.org.br/forum/grupo/4/topico/adicionar/

2) Já o botão para editar um tópico inicial tem que levar para a mesma tela que o adicionar, inclusive para permitir a edição da categoria.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Tem só que alterar o espaço para edição da proposta. Tá muito pequeno pode aumentar em 3x
Depois pode colocar direto em produção.

**Comment by leonardocsantoss** [comment]
Ajustado. Em produção.

**Comment by josircg** [comment]
O administrador do grupo também tem que poder editar os tópicos.

Exemplo de tópico que não pode ser editado com o login josir:

http://www.raiz.org.br/forum/grupo/3/topico/7/

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Ainda sobre o layout:

3) Colocar a cor de fundo ainda mais clara. Colocar a nome do autor em negrito.

4) Existe um espaço muito grande entre o topo do quadro e o título. Temos que diminuir. 

5) Ainda temos tópicos que não estão mostrando o nome da pessoa no início. Exemplo:

http://www.raiz.org.br/forum/grupo/3/topico/25/

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Só permitir que a pessoa inclua um tópico ou um comentário se ela estiver inscrita no grupo, caso o atributo privado esteja marcado.

Caso o grupo seja privado, morre a regra de incluir a pessoa automaticamente no grupo.

**Comment by leonardocsantoss** [comment]
para ficar mais claro:

1. Se o grupo for **Aberto**:
   - Permite adicionar tópicos e comentários;
   - Adiciona automaticamente o usuário no grupo;
2. Se o grupo for **Fechado**:
    - **Não** permite adicionar tópicos e comentários;
    - Adiciona a mensagem para ele se inscrever no grupo;
    - Caso ele se inscreva, aprovar direto a inscrição sem precisar mandar email. 

Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
* Se o grupo for privado, não mostrar a estrela caso ele esteja não inscrito....
* A pergunta tem que ficar em um quadro a parte.
* A pergunta no comentário tem que incluir o nome do grupo, igual temos na pergunta que inclui no meu commit.

Depois pode colocar tudo em produção.

**Comment by leonardocsantoss** [comment]
Ajustado. Ainda está apenas no ambiente de teste.

**Comment by leonardocsantoss** [comment]
Em produção.
