### ISSUE TITLE
Erro na inclusão de um novo membro

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#123]
Não sei como mas um colaborador fez o seu cadastro sem preencher o email!!

http://www.raiz.org.br/admin/cadastro/membro/3796/

Temos que fazer uma revisão completa para que saibamos sempre como uma inclusão foi feita para tipo de formulário. No log atualmente só aparece como usuário sys mas não há referência de qual rotina fez a inclusão.

**Comment by leonardocsantoss** [comment]
Olhando o histórico de logs desse dia vi que tinha sido inserido 2 Membros, e não tinha nenhum log da inserção.

Olhando o código, vi que o problema estava nas rotinas de "Importação em lote" #23 da tela de Pessoa, que não tinha logs quando adicionava uma Pessoa, e na rotina de "Importar visitantes e colaboradores" #100, que além de não ter logs, não fazia a verificação do email antes de adicionar uma Pessoa/Membro.

As demais rotinas de criação de Pessoa/Membro estão funcionando normalmente.

Fiz os ajuste, mais coloquei apenas no ambiente de testes.
