### ISSUE TITLE
Tela da Transferência

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#125]
1) O campo de Referência não pode ser obrigatório.

2) O campo de valor não está aceitando vírgula (tem que ser BRDecimalField()

3) Incluir o PowerButton: Visualizar Caixa igual temos no Radix.

4) O Campo de Transferência Associada tem que ser o último campo. Ele gerou corretamente a contra-partida mas não está mostrando na tela.

http://www.raiz.org.br/admin/financeiro/transferencia/368/

**Comment by leonardocsantoss** [comment]
Resolvido, Coloquei apenas no ambiente de testes.
