### ISSUE TITLE
Cadastro de Pagamentos

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#127]
1) Tooltip na Despesa: 'Preencha caso seja um pagamento de uma despesa já agendada'

2) Referência não pode ser obrigatória (essa eu já fiz)

3) Incluir o botão de Visualizar Caixa (igual temos no Radix)

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
Implementar o padrão de localized=True diretamente no PowerAdmin para que não se tenha que definí-lo em todas as telas do módulo financeiro. Temos várias telas em que o sistema não está aceitando valores como 14,50

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei direto em produção.
