### ISSUE TITLE
Mover um tópico de um grupo para o outro

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#129]
Se o usuário corrente for o autor da tópico ou o administrador do grupo, temos que incluir uma opção no menu: "Mover Tópico" para que ele possa mover um tópico para outro grupo. 

Ao clicar nela, deve-se abrir um painel que mostre os grupos do mesmo escopo (Nacional,Estadual,Municipal) do grupo corrente para que ele possa selecionar o grupo.

Temos que ter um checkbox "Listar Nacionais" para que ele mostre apenas os grupos nacionais.

**Comment by leonardocsantoss** [comment]
Coloquei apenas no ambiente de testes.

Achei muito estranho e limitado essa ideia do check para mostrar só os nacionais. Ex.: Se eu estiver movendo um tópico nacional, só poderei mover ele para um grupo nacional.

Então eu estou trazendo apenas os grupos que o usuário participa. E fazendo a separação destes pelo escopo.

**Comment by josircg** [comment]
Ficou ótimo! 

Ao final da rotina, temos que gravar uma conversa indicando "Tópico transferido do grupo "xxxx"

**Comment by leonardocsantoss** [comment]
Resolvido. Em produção.
