### ISSUE TITLE
Tópicos Recentes

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#130]
1) Incluir Tooltip para o menu lateral. Esse tooltip não pode ficar sobre o link para não atrapalhar o clique do usuário.

Recentes - Mostra todas as conversas ativas mais recentes da Teia
Não Lidos - Tópicos não lidos desde a sua última visita a Teia
Meus grupos - Lista dos grupos do qual você participa
Diretório - Lista todos os grupos existentes
Pesquisa - Permite pesquisar um tópico por assunto

2) Resumo do que deve ser listado nos Tópicos Recentes:

Propostas em aberto
Tópicos marcados com estrela
Tópicos recentes ordenados pela data de atualização que NÃO estejam fechados

* Temos que incluir um título para cada seção igual temos no Loomio
* Falta implementar o filtro do que não está fechado.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
* Temos que incluir um título para cada seção igual temos no Loomio

**Comment by leonardocsantoss** [comment]
Ajustado.

**Comment by josircg** [comment]
A marcação de estrela nos tópicos não está funcionando. Quando o usuário move o mouse para a estrela, aparece o tooltip mas nada acontece quando o usuário clica sobre a estrela. O tooltip não pode ficar sobre a estrela.

Exemplo: http://teste.raiz.org.br/forum/grupo/3/topico/5/

**Comment by leonardocsantoss** [comment]
O problema era só o tooltip que estava por cima do link.
