### ISSUE TITLE
Armazenar histórico de uma conversa editada

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#132]
Nova classe ConversaHistorico

1) Sempre que o usuário editar uma conversa, deve-se armazenar em ConversaHistorico a conversa original e setar o atributo Conversa.Editada.

2) Mostrar o link "Editado"  na visualização da conversa caso o campo esteja preenchido. Ao clicar no link, abrir um uma nova janela listando a conversa atual e as conversas de ConversaHistorico ordenando pela mais recente para a mais antiga:

3) Na janela, incluir um botão de "Retornar" que irá retornar ao tópico da conversa original.

![historico](https://cloud.githubusercontent.com/assets/634507/21136401/adc0f004-c10c-11e6-8f84-86f1e43cb7c9.png)

4) Ao excluir uma conversa, excluir também o histórico.

5) Aproveitamos para corrigir o erro de que o editor passava a ser o criador do tópico quando havia uma edição.

**Comment by josircg** [comment]
Eu tentei fazer os itens (1), (2) e (5) mas não consegui tempo para terminar!

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Acho que faltou colocar o link "Comentário Editado" no tópico original: 

http://teste.raiz.org.br/forum/grupo/5/topico/9/
Também deveria aparecer o link no tópico principal.

**Comment by leonardocsantoss** [comment]
Ajustado e em produção.
