### ISSUE TITLE
Paginação do tópico

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#134]
1) Erro no botão Próximo: quando se clica nele, dá erro.

http://www.raiz.org.br/forum/grupo/3/topico/25/

2) O botão tem que ficar mais visível, no canto esquerdo e com a mesma cor dos outros botões.

3) Ao entrarmos no tópico, deve-se ir direto para a última página.

4) Se certificar que na segunda página, há a possibilidade de voltar para a primeira página.

**Comment by josircg** [comment]
5. O tópico inicial deve aparecer em todas as páginas.
6. O botão anterior deve aparecer logo após o tópico anterior. O texto deve ser "Conversas anteriores"

**Comment by leonardocsantoss** [comment]
Itens, 1) 2) 3) e 4) tinha feito antes, mais esqueci de comentar a issue;
Itens 5) 6) resolvido.

Coloquei direto em produção.
