### ISSUE TITLE
Colocar Item do Menu colapsado no smartphone

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#14]
Quando acessamos o site por smartfone, e clicamos em um item de menu, o site abre o item, mas não focaliza o texto. Eu inicialmente achei que não estava abrindo, mas aí vi que estava aberto lá pra baixo. O Site precisa focalizar o item selecionado nos menus.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei para que aquando acessar via mobile ele já abra posicionado na parte do site.

Além disso, coloquei para que o menu lateral apareça em baixo do conteúdo. Antes estava aparecendo em cima.

**Comment by josircg** [comment]
Dá uma olhada como esse site resolve o problema no smartphone:

http://podemos.info/el-ayuntamiento-de-madrid-impulsa-una-auditoria-de-la-deuda-para-ahorrar-1-100-millones-en-2015/

Dá pra fazer?

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
No acesso por smartphone, acho que seria melhor que o menu lateral aparecesse antes dos destaques/notícias, pois são os acessos mais importantes para “vender o peixe” para o nosso público.

**Comment by josircg** [comment]
O cadastro do colaborador no smartphone está aparecendo no final, ou seja, o painel da direita tem que aparecer abaixo ou então nem aparecer.

**Comment by leonardocsantoss** [comment]
Ajustado e em produção.
