### ISSUE TITLE
Implementar a busca

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#17]
Somente pelos títulos e textos do artigo

**Comment by josircg** [comment]
O botão de busca saiu do layout. Temos que colocar uma lupa antes da rede social, por exemplo e abrir um form específico para a busca.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
A paginação da busca não está funcionando.

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei direto em produção.
