### ISSUE TITLE
Implementar o login pela página do site

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#18]
1) O reenviar senha não está funcionando ou pelo menos não está gravando nos emails agendados.
2) Tem que incluir na página um botão para "Login via Redes Sociais"

**Comment by leonardocsantoss** [comment]
1) Ativei as urls:

http://teste.raiz.org.br/login/
http://teste.raiz.org.br/password_reset/
http://teste.raiz.org.br/password_reset/done/

Refiz o form, para que o email seja enviado pelo agendaemail.

**Comment by josircg** [comment]
A rotina está com um erro grave. Quando o usuário ainda não tem email e ele clica em

http://teste.raiz.org.br/password_reset/

só que a rotina tem criar o usuário caso já exista membro! Hoje ele testa apenas se o usuário existe.

**Comment by leonardocsantoss** [comment]
O User já é criado automaticamente quando o Membro é salvo. Dessa forma, todo Membro vai ter um User associado.
