### ISSUE TITLE
Listagem dos GTs

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#19]
View /gts que liste os GTs existentes:

Circulo.objects.filter(tipo='G',oficial=True)

Nome (com link para site_externo)
Descrição

**Comment by leonardocsantoss** [comment]
Resolvido. http://teste.raiz.org.br/gts/

**Comment by josircg** [comment]
Dá só um espaço maior entre um registro e outro.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
Esqueci só de pedir para deixar ordenado pelo nome.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
A listagem dos círculos no site não está paginando. Só está mostrando os primeiros itens.

http://www.raiz.org.br/circulos-ident/

http://www.raiz.org.br/admin/cadastro/circulo/?o=1&tipo__exact=T
