### ISSUE TITLE
Adicionar a app django-municipios

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#2]
https://github.com/znc-sistemas/django-municipios

1) Repare que tem que importar a base completa.

2) Tem que remover a classe UF da app de cadastro e utilizar a do Django Municipios. Mas mantem o cadastro manual da cidade. Vamos fazer a crítica em um 2o momento.

3) Utilizar as tabelas nos formulários de cadastro.

**Comment by leonardocsantoss** [comment]
Resolvido.
