### ISSUE TITLE
Formulários de Visitantes / Colaborador / Filiado

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#21]
1) Novo formulário de filiados

2) Verificar se o email da pessoa já existe via ajax e não permitir a duplicidade. Nesse caso, temos que pedir para ele fazer o login no site para que possa alterar seus dados.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
3) Nos 3 formulários, trazer as cidades do cadastro de municipios - mas esse tem que fazer via ajax, ou seja, trazer em função da UF selecionada.

4) Formulário de Filiado: incluir os campos de UF / Zona / Seção e Título Eleitoral.
Estes 2 campos de Zona e Seção não existem ainda.

**Comment by leonardocsantoss** [comment]
Resolvido!

**Comment by josircg** [comment]
Só um detalhe no filiado: temos que colocar zona, seção e titulo um ao lado do outro.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
4) Diminuir o edit box da zona e seção. Colocar UF e Município eleitoral na mesma linha.

5) Colocar a data de nascimento e o nome da mãe na mesma linha.

8) Dividir o formulário em 2 quadros, colocando um quadro com o título "dados eleitorais"

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
O próximo passo é testar via AJAX se o email já existe antes do Submit. Caso o email já exista, dar um aviso "Você já está cadastrado. Quer editar os seus dados atuais ?"

Caso o usuário responda que sim, deve-se enviar um email (via agendamento) para ele com um link único para a edição. Estava pensando em um utilizar esse mesmo formulário mas com um token para sabermos que é uma edição e não uma inclusão.

O email deve ter o subject: Atualização de Cadastro do Raíz.
Com o texto: 
Saudações Cidadanistas!

Você recebeu este email pois solicitou a alteração dos seus dados através do site.

Para editar os seus dados, clique aqui: [Link]

Atenciosamente,
Raiz Movimento Cidadanista

**Comment by josircg** [comment]
A mensagem do "Clique aqui" está muito pequena. As pessoas não estão enxergando que tem que clicar.... Aumente por favor.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei direto em produção.

**Comment by josircg** [comment]
Tentei subir o novo email de boas vindas mas não consegui testar.
Coloquei o template em 2 lugares diferentes para vc ver onde fica melhor.

**Comment by leonardocsantoss** [comment]
Josir, o email não está no repositório.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes. Ex.: http://teste.raiz.org.br/admin/cms/emailagendado/6/

**Comment by josircg** [comment]
Você acredita que NENHUM usuário consegue ver o link do "Clique aqui" ?

Caso o email ou o nome já existam, tem que colocar uma div bem grande como se fosse uma caixa de diálogo com botão com o fundo VERDE e o texto em branco bem grande e remover todos os outros campos.

**Comment by leonardocsantoss** [comment]
Coloquei no ambiente de testes. A ideia foi usar o modal do próprio bootstrap.

**Comment by josircg** [comment]
O cadastro está sem as informações dos dados financeiros. Pensei que você estava usando o mesmo formulário para não duplicarmos o código. Não dá para fazer assim ?

Depois desse ajuste, pode colocar em produção. Repare que eu fiz um commit nesse meio tempo.

**Comment by leonardocsantoss** [comment]
Ajustado e em produção. Entrou também todo o forum.

**Comment by josircg** [comment]
1) O formulário de recadastro não está trazendo todos os campos:

http://www.raiz.org.br/admin/cadastro/membro/2/

e 

http://www.raizmovimentocidadanista.org.br/filiado/atualizar/2-286e92ec021bb30d2812/

2) Depois que o sujeito preenche o recadastramento, o link com hash ainda funciona ?

**Comment by leonardocsantoss** [comment]
1. Resolvido.

2. Sim, continua funcionando, o usuário pode fazer quantas alterações quiser com o mesmo link.

**Comment by josircg** [comment]
3) Alterar a descrição da view para:

http://www.raiz.org.br/atualizar-cadastro/

ela vai servir tanto para o membro como o para filiado. O post é que vai definir qual dos dois formulários ele irá chamar. Com isso, poderemos ter uma chamada no menu para que ele altere automaticamente o cadastro, sem precisar passar pelo formulário original.

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Pode colocar em produção!

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
Na view do Atualizar Cadastro, se o email já funcionar não precisa fazer a crítica do CPF.
Ou seja, só fazer a crítica do CPF se o email estiver em branco.

**Comment by leonardocsantoss** [comment]
Ajustado.

**Comment by josircg** [comment]
1) Veja o caso abaixo:

http://teste.raiz.org.br/atualizar-cadastro/4-473-9a698969119d315e2c52/

Hoje não temos a opção da pessoa passar de colaborador para pré-filiado! Tem que ter um segundo botão nesse recadastramento para que ele possa se tornar pré-filiado. Nesse caso, você iria abrir o segundo frame que mostra os dados eleitoriais. O nome do botão deve ser "Clique aqui caso queira se tornar um pré-filiado" 

2) No frame dos Dados Eleitorais, altere o texto do botão para "Não sabe os seus dados ? Clique aqui para fazer a consulta".

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Ficou ótimo. Só altere para "Não sabe o número do seu título de eleitor ? Clique aqui para fazer a consulta no site do TSE"

Depois disso, pode colocar em produção.

**Comment by josircg** [comment]
No formulário de Filiado, 

http://www.raiz.org.br/filiado/

caso a pessoa já seja um colaborador e queira virar um filiado, abrimos um popup e depois redirecionamos o usuário para a tela de recadastramento. Temos que mudar essa lógica para enviar o email direto e redirecionar automaticamente para a tela 

"Um email acaba de ser enviado com as instruções para edição dos seus dados"

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei direto em produção.
