### ISSUE TITLE
Template da listagem dos artigos de uma seção

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#22]
Não mostrar o heading. Só mesmo o título e a data. 
Com isso, pode diminuir bastante a altura de cada elemento.
Tem que ter também a opção de paginação (para mostrar de 10 em 10).

**Comment by leonardocsantoss** [comment]
Resolvido. Os links da paginação só vão aparecer quando tiver mais que 10 notícias. Ex.: http://teste.raiz.org.br/pesquisa/?q=a
