### ISSUE TITLE
Importação dos visitantes e colaboradores

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#23]
PowerButton na tela dos Colaboradores que fará a importação do CSV. 

Só insira o registro se o email não existir. Se o email já existir, atualize apenas os dados que estiverem em branco.

Importe somente o nome, email, uf e cidade - pode deixar que eu faço o restante da lógica.

Ao final, indique quantos registros foram lidos e quantos foram importados com sucesso.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes: http://teste.raiz.org.br/admin/cadastro/membro/
