### ISSUE TITLE
Permissão seletiva para artigos

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#25]
Repare no artigo Loomio. Ele está contido em 2 seções: Mídias Sociais e Colaboradores.

Entretanto, na seção "Colaboradores", defini que somente que estiver logado e for colaborador pode visualizar.

Dessa forma, temos que filtrar os elementos das seções em função das permissões definidas. Essa regra tem que ser incorporada também para o PowerCMS.

**Comment by leonardocsantoss** [comment]
Resolvido. Já coloquei em produção.
