### ISSUE TITLE
No "Contato" que aparece no rodapé, fazer o link para um novo formulário

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#26]
Nome:
Email: <criticar o email>
Mensagem:

No submit, enviar email para correio@raiz.org.br através dos emails agendados.

Ou envie um email para <a href=mailto:correio@raiz.org.br>correio@raiz.org.br</a>

**Comment by leonardocsantoss** [comment]
Resolvido. Já está em produção.
