### ISSUE TITLE
Erro em algum ponto da consulta por UF

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#27]
Not Found: /chaining/filter/municipios/municipio/uf//
Request Method:	GET
Request URL:	http://www.raiz.org.br/chaining/filter/municipios/municipio/uf//
Django Version:	1.4.21
Python Executable:	/var/webapp/raizcidadanista/bin/python

**Comment by leonardocsantoss** [comment]
Resolvido. Já coloquei em produção.

**Comment by josircg** [comment]
Ainda está dando erro:

Report at /chaining/filter/municipios/municipio/uf/
Not Found: /chaining/filter/municipios/municipio/uf/

**Comment by leonardocsantoss** [comment]
Espero ter conseguido resolver. Pesquisei por todas as referências a "/chaining/filter/municipios/municipio/uf/", e fiz os ajustes no js para não chamar ela quando o usuário não selecionar nenhum UF.
