### ISSUE TITLE
Mapa do Brasil

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#28]
Utilizar o script em http://ponto.me/tmp/mapa_Brasil_CSS/map.html

para desenhar o mapa e verificar se dá para colocar uma cor em função do número de círculos associados a cada estado.

Ou então partir para a ignorância e usar um modelo mais complexo já em Django:

http://django-gis-brasil.readthedocs.org/en/v0.3/

**Comment by leonardocsantoss** [comment]
O que acha de usar o googlecharts. É bem mais simples, e é possível colocar mais informações.

Fiz um exemplo: https://docs.google.com/document/d/1FEBKvikDgdZPKfDEOyf2DWalSNZAPSLyowQsIxAhjTE/edit?usp=sharing

Baixa e abre no navegador.

**Comment by josircg** [comment]
Maravilha! Pode seguir com esse do Google!

**Comment by josircg** [comment]
Ao invés de mostrar o número de círculos, utilizar o número de colaboradores de cada estado.
Fazer uma view que possa entrar como um iframe, ou seja, sem nenhum template.

**Comment by leonardocsantoss** [comment]
Resolvido: http://teste.raiz.org.br/mapa/

Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Maravilha Leonardo. Tem como associar o click a uma view?

**Comment by leonardocsantoss** [comment]
Tem sim. Basicamente preciso adicionar um listern.

```
function regionClick(region){
    console.log(region.region);
}
google.visualization.events.addListener(chart, 'regionClick', regionClick);
```

**Comment by josircg** [comment]
Maravilha. Nesse caso vamos chamar a listagem dos círculos do Estado igual já temos no Combobox.

**Comment by leonardocsantoss** [comment]
Olha se ficou legal: http://teste.raiz.org.br/mapa/

**Comment by ArbaesSolrac** [comment]
Está ficando bacana!

[s]
Carlos


2015-10-26 13:12 GMT-02:00 Leonardo C. Santos <notifications@github.com>:

**Comment by ArbaesSolrac** [comment]
Hello!

 

New message, please read <http://montear.info/seems.php?mr>

 

Carlos Seabra

**Comment by ArbaesSolrac** [comment]
Hello!

 

New message, please read <http://culturalflow.com/always.php?3wiy6>

 

Carlos Seabra
