### ISSUE TITLE
Permitir que os colaboradores se adicionem nos círculos

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#29]
Na view que lista os círculos, verificar se o usuário está autenticado. 

Caso não estejam mostrar a mensagem:

"Caso você já seja colaborador ou filiado, faça o login no sistema e adicione o seu nome nos círculos de seu interesse"

Caso esteja logado:

Verificar se o usuário já faz parte do grupo. Caso positivo, mostrar o botão "Membro do Grupo" com uma borda verde e fundo branco.

Caso negativo, mostrar o um botão "Entrar no grupo" (com o fundo verde) ao lado de cada registro. O botão irá chamar a view /entrar-grupo passando o id do grupo. A view irá adicionar o usuário no grupo.

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei apenas no ambiente de testes.

A view para adicionar o usuário no grupo ficou: /membro/entrar-circulo/<circulo_id>/

**Comment by josircg** [comment]
1) Colocar em formato de tabela:
http://www.tutorialspoint.com/bootstrap/bootstrap_grid_system.htm

2) Colocar a mensagem "Caso não seja colaborador..." no final do texto ao invés de colocar no início

3) Fazer o mesmo para a view /circulos-tematicos/

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
A view entrar-circulo não está mais funcionando:

http://www.raiz.org.br/membro/entrar-circulo/60/

**Comment by leonardocsantoss** [comment]
Josir, o único erro que peguei, foi que o sistema permitia que o Colaborador se registrasse mais de uma vez no mesmo círculo.

Vale lembrar que é preciso que o Colaborador esteja logado para entrar em um círculo.

**Comment by josircg** [comment]
1) O botão de "Entrar no Grupo" não está funcionando!

2) Aproveite para alterar o texto do botão para "Se inscrever no Grupo" 

3) Além disso, ele tem que redirecionar a pessoa para a página do grupo automaticamente.

4) Criar um outro botão "Visualizar Grupo" pois os usuários não percebem que devem clicar no nome!

**Comment by leonardocsantoss** [comment]
1. O erro acontecia quando o usuário não tinha um Membro associado. Dessa forma, quando isso acontecer não irá aparece mais o botão "Se inscrever";
2. Ok;
3. Ok;
4. Ok;
5. Ok.

Ps.: Coloquei direto em produção.

**Comment by josircg** [comment]
Novo atributo no círculo para indicar se permite cadastro pelo colaborador.

Caso não permita, não habilitar o botão para o cadastro.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Pode ir pra produção!

**Comment by leonardocsantoss** [comment]
Em produção.
