### ISSUE TITLE
Erro na visualização dos círculos 

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#3]
"Key 'tipo' not found in Form"
Request Method:	GET
Request URL:	http://teste.raiz.org.br/admin/cadastro/circulo/40/
Django Version:	1.4.21
Exception Type:	KeyError
Exception Value:	
"Key 'tipo' not found in Form"
Exception Location:	/var/webapp/raizcidadanista/local/lib/python2.7/site-packages/django/forms/forms.py in __getitem__, line 109
Python Executable:	/var/webapp/raizcidadanista/bin/python
Python Version:	2.7.6

**Comment by leonardocsantoss** [comment]
Resolvido.
