### ISSUE TITLE
O URL Migrates está funcionando parcialmente

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#32]
Sempre que eu tento acessar:

Request URL:	http://www.raiz.org.br/regras-facebook/

ele retorna a página corretamente mas depois envia o log de erro dizendo que o arquivo não existe.

**Comment by leonardocsantoss** [comment]
Não consigo solucionar o problema. Funciona da seguinte forma: Quando o sistema não encontra nenhuma url, uma middleware verificar se tem alguma url para migração.

O problema é que o sistema envia email dizendo que não encontrou nenhuma url antes de verificar a url de migração.

**Comment by josircg** [comment]
Dá uma olhada em como resolvemos isso no Radix. Talvez seja só a sequência dos middlewares ou da string url()

**Comment by leonardocsantoss** [comment]
Josir, o Raix não envia email quando temos erro 404.

**Comment by leonardocsantoss** [comment]
Resolvido.
