### ISSUE TITLE
Melhorar a performance do site

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#33]
https://developers.google.com/speed/pagespeed/insights/?url=www.raiz.org.br&tab=desktop

O Google também não pegou automaticamente o sitemap.xml mas o link está ativo.

**Comment by leonardocsantoss** [comment]
Coloquei o sitemap no robots.txt. Ex.:

Sitemap: http://www.raiz.org.br/sitemap.xml

Ativei o gzip do nginx, mais não consegui melhorar mais ainda a compressão das imagens, um detalhe é que elas estão sendo comprimidas depois que é feito o upload, e estamos usando as bibliotecas recomendadas por eles.
