### ISSUE TITLE
Início do fórum de Discussão

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#35]
Nova app para a construção do fórum. A princípio a criação dos fóruns será via admin. 

1) Estou pensando em deixar ele totalmente desplugado das outras aplicações. Para isso teremos que ter um classe mãe do tópico que é o Grupo.

Ou seja, teremos que substituir o Circulo pelo Grupo e teremos que trocar o Membro pelo User.

2) A primeira tela que teremos que montar será a que lista as mensagens de um determinado fórum. Vamos usar o boostrap mas eu queria um layout bem próximo do Facebook.

**Comment by leonardocsantoss** [comment]
1) Precisei criar as classes Grupo e GrupoUsuario. 

2) Resolvido. Ex.: http://teste.raiz.org.br/forum/grupo/1/

**Comment by josircg** [comment]
Blz. 

1) Ok

2) Não precisa ter o "Mais" - Vamos criar um box para cada tópico. Ao clicar no box inteiro, já entrarmos no tópico. Dentro do box tem que ter o título, o nome do usuário e a data. Segue um exemplo.

3) Copie o base.html para dentro da app do fórum. Sempre pense que a app não pode ter nenhuma relação com o restante das apps.

4) O próximo passo é criar um link para adicionar um novo tópico.

**Comment by josircg** [comment]
![loomio-exemplo](https://cloud.githubusercontent.com/assets/634507/10340229/85d51fec-6ce5-11e5-9d84-43b9b6c2b38c.png)

**Comment by leonardocsantoss** [comment]
2) 3) Ok.
4) A ideia vai ser fazer igual ao Radix, onde o form de adicionar fica abaixo da listagem?

**Comment by josircg** [comment]
4) Não. Ao lado do nome do grupo tem que ter um botão bem grande "Adicionar novo tópico"

**Comment by leonardocsantoss** [comment]
Coloquei apenas no ambiente de testes. Olha se ficou legal: http://teste.raiz.org.br/forum/grupo/1/

**Comment by josircg** [comment]
Tem que reajustar as telas por conta do novo layout.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
1) A gente tem que colocar cada pergunta e resposta em um box para as pessoas consigam entender o que é cada comentário. Se baseie exatamente na figura que eu coloquei acima.

2) Coloque os dados do autor e da data/hora em uma fonte menor.

**Comment by josircg** [comment]
![loomio-pauta-detalhe](https://cloud.githubusercontent.com/assets/634507/15710121/f0f270b8-27de-11e6-97e8-5173fa347025.png)

**Comment by leonardocsantoss** [comment]
Olha se ficou melhor!

Entra em: http://teste.raiz.org.br/forum/ com o usuário josir.

**Comment by josircg** [comment]
2) Ainda pode ficar menor. Retire aqueles traçinhos iniciais:
3) As margens laterais do grupo estão muito espaçadas:

http://teste.raiz.org.br/forum/grupo/1/

4) Implementar o controle de lido/não lido.

**Comment by leonardocsantoss** [comment]
2)3) Resolvidas.

**Comment by josircg** [comment]
1) O curtir/não curtir do tópico principal deve ficar antes das respostas:

http://teste.raiz.org.br/forum/grupo/1/topico/1/

2) Trocar o "Não curtir" por "Pode melhorar" e "Curtir" por "Curti". 

3) Incluir o link de "Excluir" para excluir a mensagem para as mensagens do usuário;

4) Mostrar a lista de pessoas que curtiram e não curtiram quando eu passar o mouse (via AJAX)

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
1) No tópico principal, não deve ter a opção Responder!

2) Temos que ter um método que retorne o nome curto da pessoa: caso exista o apelido, usar o apelido. Caso não exista, usar o login da pessoa. Usar para todas as visualizações do autor, inclusive para o item (5). 

5) Só abrir o mouse-over se houver algum Curtir

3) 4) 6) Ok

**Comment by leonardocsantoss** [comment]
1) 2) 5) Resolvido.

**Comment by josircg** [comment]
4) A opção de excluir só aparece nas respostas e não nos comentários livres. Exemplo em: http://teste.raiz.org.br/forum/grupo/1/topico/1/

**Comment by leonardocsantoss** [comment]
Resolvido. Lembrando que quando o usuário remove um comentário livre, todas as respostas deste são removidas.

**Comment by josircg** [comment]
Epa! Se tiver resposta, não deve ser possível remover o comentário.

**Comment by leonardocsantoss** [comment]
Ajustado.

**Comment by josircg** [comment]
1) Alterar as opções de curtir para: Ciente, Concordo, Concordo em parte, Discordo. Tem que incluir essas opções no status do comentário.

2) Colocar a cor do box das respostas um pouco mais escura ou azulada.

3) O nome do usuário ainda está aparecendo completo. Veja o caso do JOSIR CARDOSO GOMES. Tinha que aparecer apenas Josir pois ele está com apelido.

**Comment by leonardocsantoss** [comment]
1) 2) 3) Resolvido.

**Comment by josircg** [comment]
1) O "desclick" não está funcionando
2 e 3) Ok

**Comment by leonardocsantoss** [comment]
1) Resolvido.

**Comment by josircg** [comment]
1) O Editar comentário ou tópico parou de funcionar. Só aparece para as respostas.

2) Vamos diminuir a fonte da letra que é mostrada em 1 pixel. 

3) Alterar o layout do tópico inicial. Tirar aquela faixa verde deixando apenas o nome do grupo. Colocar o título e o texto do tópico dentro de um quadro.

4) Colocar o botão "Responder" também nas respostas mas associar a conversa principal. Do jeito que está, o cara tem que subir na primeira conversa para conseguir responder.

5) Após responder, tem que posicionar a visualização para o final da conversa. Hoje a tela está voltando para o início.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
3) A Faixa verde continua aparecendo. Aproveite e coloque novamente o "Teia > {{ Nome do Grupo }}" onde Teia será um link para /forum/diretorio/

6) Coloque uma borda preta no tópico inicial para diferenciá-lo das respostas.

**Comment by leonardocsantoss** [comment]
3) Resolvido. Além disso foi colocado o topo fixo quando rola a página.
6) Resolvido.
