### ISSUE TITLE
Validação dos emails existentes

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#36]
1) Marcar todos os emails com 'N' (Não confirmado)

2) Action 'Validar Emails' na tela da Pessoa que irá enviar um email para o usuário com um link para uma view validate_email nos mesmos moldes do reset da senha.

3) Quando o usuário receber o email e validar o email, a view irá marcar o email da pessoa com o status 'A'.

**Comment by leonardocsantoss** [comment]
1) Para isso usei o script:
```python
from cadastro.models import Pessoa
Pessoa.objects.all().update(status_email='N')
```
2) Resolvido

3) Resolvido

Ps.: Coloquei um signal para toda e qualquer pessoa cadastrada no sistema, ele envia email de confirmação. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
1) Após o cadastro, redirecionar para a página cadastro/bem-vindo.html com a mensagem "Cadastro Efetuado. Você receberá um email para que confirme seus dados"

2) A view de validação tem que redirecionar para o cadastro/bem-vindo.html e não para a Home caso contrário o usuário não consegue perceber a mensagem que aparece no meio da tela.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
Pode colocar em produção!

**Comment by leonardocsantoss** [comment]
2) O reset está lá.

Ainda não consegui identificar o problema do CMS que sumiu do menu.

**Comment by josircg** [comment]
3) enviar o email de validação de emails automaticamente, assim que a pessoa fizer o cadastro.

4) Enquanto não descobrimos o problema do Dashboard:

- inclua o Artigo, a seção e o Menu no menu.
- habilite o admin do dashboard para ver se o reset está mesmo funcionando.

**Comment by leonardocsantoss** [comment]
4) Resolvido! O nome cms é meio que uma palavra reservada do django, então quando for adicionar algo no dashboard da app cms tem que adicionar 'raizcidadanista.cms.models.MODELO', sempre!

**Comment by josircg** [comment]
Está dando erro para alguns casos:

Not Found: /validar-email/74/
Request Method:	GET
Request URL:	http://www.raizmovimentocidadanista.org.br/validar-email/74/?email=guillerme.alves@gmail.com
Django Version:	1.4.22
Python Executable:	/var/webapp/raizcidadanista/bin/python
Python Version:	2.7.6
