### ISSUE TITLE
Incluir módulos da Campanha e Listas na app de cadastro

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#37]

**Comment by leonardocsantoss** [comment]
Resolvido, coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Sempre que um visitante for adicionado, incluir na lista "Visitantes" se esta existir
Sempre que um colaborador for aprovado, incluir na lista "Colaboradores" se esta existir
Depois pode colocar em produção.

**Comment by leonardocsantoss** [comment]
Ajustado e em produção.

**Comment by josircg** [comment]
Incluir a rotina de Mala Direta (que hoje temos no Radix) na tela de Pessoas.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

Ex.: http://teste.raiz.org.br/admin/cadastro/pessoa/mala-direta/

**Comment by leonardocsantoss** [comment]
Adicionei o botão "Incluir pessoas na lista".

**Comment by josircg** [comment]
Incluir ajustes feitos na rotina

**Comment by leonardocsantoss** [comment]
Ajustado. Já coloquei em produção.

**Comment by josircg** [comment]
1) Trazer como default o ckeditor na tela de inclusão e de edição. 
2) Inverter o botão para visualizar como HTML

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei direto em produção.

**Comment by josircg** [comment]
1) incluir o controle de status (Em edição, Em processamento, Finalizado); 
2) Não permitir o envio de uma nova campanha enquanto existir alguma em andamento;
3) gerar um log de quem iniciou a execução da campanha;
4) mas não precisa gerar o log de quais emails foram enviados;

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei apenas no ambiente de testes.

**Comment by leonardocsantoss** [comment]
Em produção.
