### ISSUE TITLE
Sincronizar novo colaborador que é atualmente já é visitante

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#38]
Ao cadastrar um novo colaborador, deve-se verificar se o email dele já é de um visitante. 

Caso positivo, deve-se criar o colaborador a partir do visitante na hora de gravar o novo colaborador ou filiado.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by leonardocsantoss** [comment]
Deixei o status_email permanecendo o da Pessoa(i.e. se o email já foi validado não tem porque validar novamente, e nem mandar email de validação, concorda?).

Todos os demais dados, prevalecem o do cadastro do Membro, ressalva o nome, que quando alterado é inserido um log na Pessoa com a seguinte frase:

"Nome alterado de %(antigo)s para %(novo)s pelo cadastro de Membro."

**Comment by josircg** [comment]
Ficou só com um erro. Se o membro já está cadastrado, ele dá uma mensagem errada e só depois do submit:

"Já existe um cadastro com esse email. Faça login no site para que possa alterar seus dados."

O correto seria dar a mensagem via javascript logo após a digitação do email.

**Comment by leonardocsantoss** [comment]
Ajustado.
