### ISSUE TITLE
Melhorar segurança do site

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#39]
1) Atualizar o jQuery para a versão 1.9:

Vulnerable JavaScript: http://www.raiz.org.br/static/lightbox/jquery-1.8.3.min.js
Fingerprinted jQuery below version 1.9.0.1.

2) Todo dia dá esses erros 404 - e geralmente os erros vem dos bots dos buscadores. Será que não é um erro do sitemap.xml ?

Report at /ausencia-de-reformas-bloqueou-lulismo-por-ladislau-dowbor
Not Found: /ausencia-de-reformas-bloqueou-lulismo-por-ladislau-dowbor
Request URL:	http://www.raiz.org.br/ausencia-de-reformas-bloqueou-lulismo-por-ladislau-dowbor

**Comment by leonardocsantoss** [comment]
1) Josir, infelizmente o lightbox só funciona nessa versão do jquery: 1.8.3

2)As urls no sitemap estão ok: http://www.raiz.org.br/sitemap.xml, ajustei as url para que elas reconheçam tanto o http://www.raiz.org.br/ausencia-de-reformas-bloqueou-lulismo-por-ladislau-dowbor quanto o http://www.raiz.org.br/ausencia-de-reformas-bloqueou-lulismo-por-ladislau-dowbor/
