### ISSUE TITLE
Refactoring dos Grupos

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#4]
Com os novos tipos de grupos, temos que rever todos os fontes:

DoesNotExist at /admin/cadastro/membro/

Group matching query does not exist.
Request Method:	POST
Request URL:	http://teste.raiz.org.br/admin/cadastro/membro/
Django Version:	1.4.21
Exception Type:	DoesNotExist
Exception Value:	
Group matching query does not exist.
Exception Location:	/var/webapp/raizcidadanista/local/lib/python2.7/site-packages/django/db/models/query.py in get, line 366
Python Executable:	/var/webapp/raizcidadanista/bin/python

**Comment by leonardocsantoss** [comment]
Quando o Colaborador era aprovado, ele era colocado no grupo Membro. Agora, eu colocoquei no grupo Colaborador.
