### ISSUE TITLE
Action "Criar Fórum de Discussão" na tela dos Círculos

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#40]
A ação irá criar um grupo novo na App do Fórum com o mesmo nome e descrição do Círculo e já adicionar todos os membros do círculo no Grupo.

Teremos que ter uma Foreign Key para o grupo pois sempre que um novo membro for adicionado no círculo, ele deverá ser adicionado também no grupo do Fórum.

Só habilitar o Action para o superuser por enquanto.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.
