### ISSUE TITLE
Rotina de Contribuições 

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#41]
Já criei os campos novos. Falta 

1) Incluir o modelo BRDecimalField() no projeto.

2) fazer o migrate.

3) adicionar no formulário de Colaboradores e Filiados. No combobox que aparece no formulário, não considerar o tipo "S", e "N"

**Comment by leonardocsantoss** [comment]
Coloquei apenas no ambiente de testes.

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
Criar uma função Membro.vr_pagar() O valor a pagar é calculado da seguinte forma:

se contrib_prox_pgto > mes

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes. A lógica do vr_apagar ficou:

```python
def vr_apagar(self, data):
    if self.contrib_prox_pgto and (self.contrib_prox_pgto.month == data.month and self.contrib_prox_pgto.year == data.year):
        return self.contrib_valor
    elif self.contrib_prox_pgto and self.contrib_prox_pgto > data:
        return Decimal(0.0)
    return self.contrib_valor
```

**Comment by josircg** [comment]
3) Se o usuário não selecionar nenhum item, marque todos automaticamente.
4) Inclua a coluna do tipo de pagamento (Mensal, Trimestral, etc)
5) No cabeçalho, colocar o mês corrente: Estimativa de Recebimento - Novembro 2015
6) Ao invés de gerar um HTML, gerar logo um PDF.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
1) Incluir um filtro por Estado do contribuinte;
2) Retirar a obrigatoriedade da digitação do colaborador, ou seja, será possível cadastrar uma receita sem que se preencha o colaborador.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
Deu erro :(

Request URL:	http://www.raiz.org.br/admin/financeiro/receita/add/
Exception Type:	NameError
Exception Value:	global name 'self' is not defined
Exception Location:	/var/webapp/raizcidadanista/raizcidadanista/raizcidadanista/financeiro/models.py in pagamentoidentificado_receita_signal, line 62
Python Executable:	/var/webapp/raizcidadanista/bin/python
Python Version:	2.7.6

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
Incluir um novo atributo Receita.Nota TextField() para que o usuário possa incluir uma nota explicativa na receita.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei direto em produção.

**Comment by josircg** [comment]
Verificar se já existe alguma outra receita do mesmo colaborador 5 dias antes ou depois da data informada. Caso exista, indicar aviso. Utilizar as duas datas para a verificação.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.
