### ISSUE TITLE
Redirect do formulário padrão de senha do admin

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#42]
Temos que matar o formulário de Login do Admin que é chamado quando o login não existe, ou seja, temos que mostrar aquele que aparece quando o usuário não está logado.

O usuário tem que ser redirecionado para a tela de login do site.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
1) Alterar a mensagem "Seja Bem vindo" quando o cara faz o login correto para

"Você foi autenticado com sucesso. Para acessar o ambiente administrativo, clique aqui"

2) Retirar o botão cinza do Admin que aparece no topo ao lado da pesquisa.

**Comment by leonardocsantoss** [comment]
Ajustado e em produção.

**Comment by josircg** [comment]
Quando a pessoa tenta acessar um link e não está logada, o sistema traz a tela de login corretamente.

Entretanto, após o login o redirect para o link original não é feito.

**Comment by leonardocsantoss** [comment]
Resolvido, coloquei direto em produção.

**Comment by josircg** [comment]
1) Troque o título "Entrar" para "Autenticação"; Tem um espaço muito grande entre o cabeçalho e o título (parece que é um problema do template e não dessa tela especificamente).

2) No celular, os botões de login alternativo estão grudados;

3) Permitir que se cadastre o email além de cadastrar o login;

4) Esse pode ficar para depois pois não sei a complexidade de fazer isso: Incluir um checkbox "Lembre do meu login nessa máquina" e gravar um cookie para que o sistema faça o login da próxima vez automaticamente;

**Comment by leonardocsantoss** [comment]
1) 2) ok
3) Você quis dizer "login" em vez de cadastre, certo?
4) Resolvido.
