### ISSUE TITLE
Comentários dos artigos

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#43]
Dá uma olhada no formulário para comentários:

http://www.raiz.org.br/nota-de-repudio

Tem um campo ativo?! Pra que serve isso ?
Temos que implementar o recaptcha pois começou a aparecer spam.

**Comment by leonardocsantoss** [comment]
Ajustado. Já coloquei em produção.

**Comment by josircg** [comment]
Temos que criar um admin apenas para os comentários. Do jeito que está, fica impossível de remover os comentários que estão no artigo.

**Comment by leonardocsantoss** [comment]
Pronto. Já coloquei em produção.
