### ISSUE TITLE
Email de envio de reset de senha está desformatado.

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#44]
http://www.raiz.org.br/admin/cms/emailagendado/548/

**Comment by josircg** [comment]
Aproveitando: altere o formulário de contato para colocar no from, o email da pessoa que preencheu o formulário.

http://www.raiz.org.br/admin/cms/emailagendado/2269/

**Comment by leonardocsantoss** [comment]
Resolvido. Eu precisei criar o campo from_email no EmailAgendado para poder enviar o email com o from: email da pessoa que preencheu.

Coloquei todas as alterações apenas no ambiente de testes.

**Comment by leonardocsantoss** [comment]
Alterei para colocar com reply-to. Dessa forma, removi o campo from_email. Ainda está apenas no ambiente de testes.

**Comment by josircg** [comment]
Pode colocar em produção!

**Comment by leonardocsantoss** [comment]
Em produção.
