### ISSUE TITLE
Validação dos emails / Log

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#46]
1) Quando o usuário responder o formulário de atualização de cadastro, já marcar o status_email como ativo.

2) Registrar no log do colaborador que o formulário de atualização de cadastro foi preenchido.

3) PowerButton "Colaborador" na tela da pessoa para ir direto para a tela do colaborador  caso ele também seja um colaborador.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Deu erro mas o email não veio pra mim. Coloca o debug=true para facilitar os testes.

**Comment by leonardocsantoss** [comment]
Pronto. Ativei o debug.
