### ISSUE TITLE
Data de Pré-Filiação

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#47]
1) Criar novo campo Membro.dt_prefiliacao DateField(), aceitando nulo para registrar a data de pré-filiação.

2) Mostrar no grid do Filiado.

3) Popular o campo da seguinte forma: se houver registro de contribuição ou com o nome da mãe, colocar como 1/11/2015.

4) No formulário de cadastro do pré-filiado, gravar com a data corrente.

**Comment by leonardocsantoss** [comment]
1) 2) ok.
3) Usei o seguinte script:
```python
from cadastro.models import Membro
from datetime import date

dt_prefiliacao = date(year=2015, month=10, day=1)
for membro in Membro.objects.filter(filiado=True):
    membro.dt_prefiliacao = dt_prefiliacao
    if membro.dtcadastro > dt_prefiliacao:
        membro.dt_prefiliacao = membro.dtcadastro
    membro.save()
```
4) ok.

Coloquei apenas no ambiente de testes. Já rodei o script lá.

**Comment by josircg** [comment]
Tá errado. Ficou faltando colocar o filtro do nome da mãe!

Ou seja, só colocar a data, se for filiado e também se atender ao critério de ter o nome da mãe preenchido.

**Comment by leonardocsantoss** [comment]
Ajustado. Rodei novamente no ambiente de testes.

**Comment by josircg** [comment]
Eu atualizei os dados do cadastro abaixo mas ele a data de pré-filiação não foi preenchida.

http://teste.raiz.org.br/admin/cadastro/membro/4/

**Comment by leonardocsantoss** [comment]
Tinha colocado apenas no formulário de cadastro do pré-filiado. Coloquei em um signal, para sempre que salvar um Membro, se não tiver a dt_prefiliado preenchida, coloca a data corrente.

Está apenas no ambiente de testes.

**Comment by josircg** [comment]
Pode colocar em produção.

**Comment by leonardocsantoss** [comment]
Em produção.
