### ISSUE TITLE
Novos campos para os Membros

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#48]
Precisaremos de 3 campos (estadocivil, endereco, endereco_num, endereco_complemento.

1) Estado Civil: com as opções:

S-Solteira(o)
C-Casada(o)
E-Separada(o)
D-Divorciada(o)
V-Viúva(o)

2) Endereço com 100 caracteres, Número: 10 caracteres. Complemento: 20 caracteres.

Não habilitar esses campos ainda em nenhum formulário externo.

Aproveite para agrupar os campos (telefone,celular), (secao,zona,titulo) em uma única linha na tela de edição do Admin.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
1) Inclua por favor um filtro pelo campo Fundador na tela dos Membros. 

Já no formulário:

2) Coloque o CEP, UF e Municipio na mesma linha

3) O texto é "Complemento" - está "Completo" e coloque do lado do número.

Depois pode colocar em produção.

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
4) Tem que colocar todos os campos obrigatórios com o (*)

5) Tem que dar um maior destaque ao Checkbox do "Quero assinar" - coloque em verde e em negrito.

**Comment by leonardocsantoss** [comment]
Ajustado.
