### ISSUE TITLE
Action "Atualização Cadastral" na tela dos Membros

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#49]
1) Irá buscar o template da Campanha "Atualização Cadastral" e enviará 

Repare que o HTML da campanha tem uma variável {{form}} que deverá conter um link para a página 

{{site}}/atualizacao/{{hash}}

onde o {{hash}} será um hash individual para o membro.

2) Montar uma view /atualizacao/

que irá trazer o formulário de filiados com os dados do membro. 

3) Alterar o formulário de Filiados para incluir os campos de endereço, estado civil e um checkbox "Quero assinar a ata de fundação da RAiZ" (será o campo novo Fundador)

Caso o checkbox esteja marcado os seguintes campos serão obrigatórios: nome completo, estado civil, profissão, título de eleitor (número, zona e seção), número de inscrição no CPF, e endereço completo (rua, número, cidade, estado e CEP).

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
Tem vários usuário que quando clicam, o navegador leva para o site mas não incluem a barra final e aí o sistema não acha.

Not Found: /atualizar-cadastro/16x-4bs-185b650f4ed9e7e3bc66

Tem como resolver isso?

**Comment by leonardocsantoss** [comment]
Resolvido. Com / ou sem / vai funcionar.
