### ISSUE TITLE
Novo IFrame para busca dos círculos

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#5]
Criar um iFrame que faça a busca dos círculos igual ao que temos no site original. O iFrame será chamado pelo artigo Círculos

**Comment by leonardocsantoss** [comment]
Iframe criado: http://teste.raiz.org.br/circulos/

**Comment by josircg** [comment]
1) temos que colocar na mesma fonte do site
2) coloque um círculo em cada linha. Agora já tem espaço :)

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
1) Incluir uma busca pelo nome da cidade do círculo. 

2) Nos links para os círculos, sempre abrir uma janela nova.

**Comment by leonardocsantoss** [comment]
1) 2) Resolvidos. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Coloque o texto assim: "Ou então busque pelo nome da cidade".

Caso não ache nenhum, mostre o texto: "Caso a sua cidade não esteja listada, busque o círculo estadual ou então crie o primeiro círculo na sua cidade!"

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei direto em produção.
