### ISSUE TITLE
Action Requerimento

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#50]
Gerar um PDF se baseando no modelo anexo para os colaboradores marcados.

**Comment by josircg** [comment]
[REQUERIMENTO CARTÓRIO.docx](https://github.com/josircg/raizcidadanista/files/45687/REQUERIMENTO.CARTORIO.docx)

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Esse pode colocar direto em produção.

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
1) O TE tem que ser o Título Eleitoral!
2) Tem como alterar o solteiro(a) para solteiro ou solteira ?

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
- Colocar o UpperFirst nos nomes
- Colocar 6 pessoas por página espaçando mais para as assinaturas.

**Comment by josircg** [comment]
No requerimento, tem que incluir a naturalidade logo depois do TE. Exemplo: 

TE n. 0078 2473 0647, zona 15, seção 15, natural de Ponta Grossa/PR

Caso esteja em branco, utilizar a mesma cidade e UF do endereço.

**Comment by josircg** [comment]
Eu tive que alterar para 6 pessoas por página. Quando eu fiz isso, o cabeçalho quebrou!

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei direto em produção.

**Comment by josircg** [comment]
Tanto o agrupamento como o cabeçalho devem sair pelo UF eleitoral e não pela UF do domicílio.

**Comment by leonardocsantoss** [comment]
Ajustado.

**Comment by josircg** [comment]
Novo Action: Requerimento em Texto.

Ao invés de gerar um PDF, montar apenas um HTML sem nenhuma formatação ou quebra de página.

E nesse tem que incluir também o **E-MAIL e o primeiro TELEFONE.

**Comment by leonardocsantoss** [comment]
Pronto. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Leonardo ,tinha que ficar exatamente ao texto que eu coloquei. Eu já fiz a correção mas faltou colocar a numeração.

**Comment by leonardocsantoss** [comment]
Ajustado. Eu não tinha visto o teu exemplo.

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
Temos que alterar a geração do Requerimento para as seguintes regras:

* Número e nome em bold
* Nome: Iniciando com maiúscula cada palavra
* Sexo: minúscula
* Estado civil: minúscula
* At. profissional: minúscula
* Endereço: Iniciando com maiúscula cada palavra
* Endereço: faltou incluir o complemento
* Todas as separações com vírgulas
* Nenhum espaço antes da vírgula
* Um único espaço após a vírgula
* terminando em ponto e vírgula

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei direto em produção.

**Comment by josircg** [comment]
foi pedido nacionalidade, estado civil e profissão em minúsculo e ainda saiu em caixa alta.

**Comment by leonardocsantoss** [comment]
Confundi minúsculo com maiúsculo. Fiz os ajustes e coloquei direto em produção.
