### ISSUE TITLE
Incluir 2 campos novos no formulário de Filiados.

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#52]
Novos campos UF_Naturalidade e Cidade_Naturalidade aceitando Null.

No formulário de Filiação, colocar logo abaixo do Endereço dentro do mesmo quadro. 

Mesmo formato de UF e Cidade. Preencher por default com o mesmo valor da cidade do Endereço.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
Após o preenchimento da UF, o sistema sugere a primeira cidade do Estado e aí grande parte dos usuários NÃO está preenchendo esse campo corretamente.

O problema ocorre para os 3 campos de Município!

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei direto em produção.

**Comment by josircg** [comment]
Já recebi reclamação de vários usuários que dizem que não conseguem se cadastrar como colaboradores. O formulário dá a mensagem de erro de que todos os campos devem ser preenchidos mas não mostra qual está faltando.

Em todos os casos, o erro só ocorre quando a pessoa é visitante. Eu não consegui reproduzir o problema.

Tente reproduzir o erro no IE ou no celular ou analisando o código.

**Comment by leonardocsantoss** [comment]
Fiz vários testes e não consegui simular o erro. Então coloquei para o sistema enviar email para os ADMIN quando houver uma tentativa de cadastro.

https://github.com/josircg/raizcidadanista/blob/master/raizcidadanista/cadastro/views.py#L112
