### ISSUE TITLE
Envio de confirmação de pagamento por email

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#53]
Sempre que uma nova receita for adicionada, enviar um email para o colaborador c/c oculta para os usuários que forem do perfil "Financeiro"

Assunto: Pagamento Identificado!

Texto do email:
------
Seu pagamento já foi identificado.

Aproveite a oportunidade para ver a nossa prestação de contas dos últimos 3 meses:

http://www.raiz.org.br/associacao/

Muito obrigado pela sua contribuição!

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei direto em produção.

**Comment by josircg** [comment]
Hoje o email está sendo enviado na inserção. Vamos alterar para enviar apenas quando a data da conciliação não for nula (tanto na inserção quanto na atualização).

**Comment by leonardocsantoss** [comment]
Ajustado.
