### ISSUE TITLE
Gauge da Campanha de Arrecadação

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#56]
1) Nova classe na app Financeira: MetaArrecadacao "Metas de Arrecadação"

descricao char(100)
data inicial
data limite
valor

2) Montar uma view que mostre um gráfico nos mesmos moldes do podemos que mostre a Meta de Arrecadação e o valor já arrecadado. O valor já arrecadado serão todas as receitas que estiverem no intervalo indicado.

Veja um exemplo em:

https://participa.podemos.info/es/microcreditos

Repare que a view deve retornar apenas uma div ou frame para que a gente possa inclui-lá em alguma parte do site.

**Comment by leonardocsantoss** [comment]
Resolvido...

Meta de exemplo: http://teste.raiz.org.br/admin/financeiro/metaarrecadacao/1/
View: http://teste.raiz.org.br/meta/1/
View dentro de um artigo como iframe: http://teste.raiz.org.br/fundacao-do-partido-raiz

Veja que criei essa Receita(http://teste.raiz.org.br/admin/financeiro/receita/1/) de exemplo dentro do limite da Meta, só para termos um exemplo.

Ps.: Coloquei apenas no ambiente de testes.

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
1) Ficou muito lento. Tem jeito de melhorar a performance?

2) Retire a data limite da meta do título. Fica parecendo que as arrecadações foram feitas até o dia limite.

**Comment by leonardocsantoss** [comment]
1) A página só tem um js do google, aqui levou 1.6s para carregar.

2) Ajustado.

**Comment by josircg** [comment]
Incluir um botão no iframe que chame uma nova tela que mostre as receitas obtidas.

A tela terá uma busca por mês e listará a data do depósito e o valor (sem mostrar o nome do colaborador).

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
Colocar logo abaixo do gráfico, antes do botão a mensagem

"Apenas XX % dos colaboradores e pré-filiados contribuíram. Vocẽ já fez a sua contribuição ?"

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei direto em produção.
