### ISSUE TITLE
Novo atributo "Público" em CirculoMembro

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#58]
Habilitar o campo no inline dos círculos.

Alterar a visualização dos dados do círculo no Mapa e também na listagem dos círculos para incluir os administradores do círculo que tenham o atributo Público marcado.

A visualização deve conter (1) nome do colaborador (2) telefone e (3) link para um formulário de contato especial onde o que o usuário digitar vai direto para o colaborador c/c correio@raiz.org.br

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by leonardocsantoss** [comment]
Em produção.
