### ISSUE TITLE
Network is unreachable

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#59]
<urlopen error [Errno 101] Network is unreachable>
Request Method:	POST
Request URL:	http://www.raiz.org.br/nota-de-repudio
Django Version:	1.4.22
Exception Type:	URLError
Exception Value:	
<urlopen error [Errno 101] Network is unreachable>

**Comment by leonardocsantoss** [comment]
Não consegui simular o erro.
Veja que consegui fazer até um comentário nessa notícia, e tudo funcionou perfeitamente.

Me manda email com o log completo do erro.

**Comment by josircg** [comment]
Leonardo, tente buscar na Internet o que gera esse erro.
