### ISSUE TITLE
"Meu Perfil" e "Logout"

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#60]
No topo do site, ao lado do Bem vindo <login> colocar 2 links "Meu Perfil" e "Logout" que ficam habilitados depois do usuário fazer o login.

Chamar view /meu_perfil que mostrará:

1) status: se é colaborador ou filiado 
2) Dados pessoais básicos
3) Botão para Atualizar os dados (chama a tela que já existe hoje)
4) Botão para redefinir a senha.
5) Listagem com os círculos a que pertence
6) Listagem com as contribuições que ela já fez

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Ficou ótimo. Pode colocar em produção!

**Comment by josircg** [comment]
Ao invés de colocar abaixo do nome, coloque ao lado. Pode colocar direto em produção.

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei direto em produção.

**Comment by josircg** [comment]
Após o inline dos grupos, incluir o texto "Caso queira se cadastrar em algum outro círculo da Raiz para receber os informes, clique aqui".

O clique aqui irá direcionar para a view: http://www.raiz.org.br/circulos-ident/

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei direto em produção.

**Comment by josircg** [comment]
1) O formulário do Meu Perfil deve gerar log da alteração de nome, CPF, telefones, endereços e dados eleitorais.

2) As letras do formulário estão muito claras. tem que mudar para preto-muito-preto :)

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei direto em produção.

**Comment by josircg** [comment]
O contorno dos campos que devem ser editados está muito tênue. Isso confunde o usuário que quer ir para um campo específico. Coloque em preto com uma linha mais grossa. Já deixe esse css pronto para usarmos em outro formulário também.

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei direto em produção.

**Comment by josircg** [comment]
1) Temos que colocar o tipo de contribuição e o valor em uma única linha logo abaixo do telefone.

2) Sexo, Estado Civil e Profissão pode ficar na mesma linha e depois do Endereço.

3) Na tela em que mostramos o agradecimento pelo preenchimento, colocar um link "Cadastre também os seus talentos e como você se voluntariar para ajudar na Raiz"

**Comment by leonardocsantoss** [comment]
1) Ok;
2) Coloquei abaixo dos dados de Naturalidade, antes de "Dados de endereço" para não misturar as coisas.
3) Ok. Mais essa página "/meus-talentos" ainda não existe.

Coloquei direto em produção.
