### ISSUE TITLE
Cadastro dos Membros de um Círculo

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#61]
1) Trocar o Combobox do Inline dos Membros por uma seleção via Popup.
2) Deixar o inline ordenado pelo nome do Membro
3) Não permitir incluir 2 vezes o mesmo membro no círculo
4) Criar um campo no círculo que calcule o total de membros do círculo.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by leonardocsantoss** [comment]
Em produção.
