### ISSUE TITLE
Alteração nos formulários de Cadastro

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#64]
1) Novo campo "Apelido ou Alcunha" tanto no formulário de colaboradores e filiados

2) CPF passa a ser pedido e obrigatório no formulário de Colaboradores (mas o campo não pode ser obrigatório na base ainda)

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
1) No formulário de Colaborador e Filiado, alterar o título para "Nome Completo (tal como consta na sua identidade)"

2) Se a UF for "Fora do Brasil", remover o combo do município e colocar um textbox com o título "País/Cidade"

**Comment by leonardocsantoss** [comment]
1) Resolvido.
2) Cadastrei o seguinte UF: http://www.raiz.org.br/admin/municipios/uf/0/

Coloquei direto em produção.
