### ISSUE TITLE
Brute Force

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#65]
Frequentemente, o site da Raiz sofre tentativas de invasão.

1) Temos que implementar a app BruteForce para travar o IP de quem tentar fazer o login via força bruta.

2) Implementar uma rotina para travar IPs de quem acessar + de 5 URLs inválidas. A ideia é que sempre antes de enviar o email do 404, incluir o IP do sujeito na base do BruteForce. Caso ele tenha mais de 5 ocorrências, não enviar o email.

**Comment by leonardocsantoss** [comment]
Eu copiei o BruteBuster para dentro do projeto e implementei o Response404Middleware. Ele registra todos os 404 por ip, salvando em FailedURLAttempt. Quando há mais de 5 tentativas por IP, ele bloqueia o usuário por 3 min, e redireciona os 404 para o PermissionDenied.

Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Mas se ainda não estiver dentro das 5 tentativas, ele envia email com o erro de URL, não é?

**Comment by leonardocsantoss** [comment]
Isso. Apensar de não ter testado, se não estiver bloqueado( antes das 5 tentativas ) a rotina continua normalmente.

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
IntegrityError at /grupos-de-trabalho/

(1062, "Duplicate entry '10.5.2.38, 177.' for key 'IP'")
Request Method:	GET
Request URL:	http://www.raiz.org.br/grupos-de-trabalho/
Django Version:	1.4.22
Exception Type:	IntegrityError
Exception Value:	
(1062, "Duplicate entry '10.5.2.38, 177.' for key 'IP'")

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei direto em produção.

**Comment by josircg** [comment]
Temos que corrigir o bruteforce pois tem chegado umas requisições que tem 2 Ips e aí dá erro de truncate na hora de incluir o registro.
