### ISSUE TITLE
Campanhas individuais

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#67]
1) Incluir um novo campo de usuário na classe Campanha e popular o campo com o usuário que criar a campanha. 

2) Caso o usuário não seja super-user, mostrar apenas as campanhas do próprio usuário.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
Os usuários não estão conseguindo usar pois a escolha das lista não está disponível. Nesse caso, teremos que permitir a seleção sem que eles possam modificar a lista.

**Comment by leonardocsantoss** [comment]
Ajustado. Troquei a lupa por um select normal.
Já coloquei em produção.

**Comment by josircg** [comment]
1) A montagem do select será baseada nas seguintes regras, independente dele ser Coordenador ou Comissão:

* Mostrar o nome dos círculos do qual ele é administrador com o texto "Membros do {nome do círculo}"
* Se ele for administrador de um círculo estadual (Local que não tenha cidade), incluir no combobox um item extra "Visitantes de <Estado>"
* Se a pessoa for super-user, mostrar as listas existentes também.

2) Na hora de enviar o email:

* Se for escolhido um círculo, ao invés de utilizar uma lista para enviar o email, enviar para todos os membros do círculo;

* Se for escolhido a opção Visitantes, enviar email para todas as pessoas do Estado;

* Se for uma lista, enviar para os membros da lista;

**Comment by leonardocsantoss** [comment]
A ideia foi adicionar 3 novos campos:

- tipo = choices(Lista, Membros, Visitantes)
- circulo_membro = FK(Circulo)
- circulo_visitante = FK(Circulo, municipio=None)

Inicialmente os campos lista, circulo_membro e circulo_visitante não vão está visíveis, eles serão mostrado de acordo com o tipo selecionado.

Fiz os filtros de permissões diretamente no admin, usando o formfield_for_foreignkey.

Ps.: Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
* No combo de Visitantes só pode aparecer os círculos estaduais (Territoriais que não tem cidade) senão você não vai conseguir filtrar os visitantes do Estado.

**Comment by leonardocsantoss** [comment]
Ajustado.

**Comment by leonardocsantoss** [comment]
Eu criei o tipo = Estadual no Círculo.

**Comment by josircg** [comment]
Altere por favor de "Estadual" para "Círculo Estadual". Depois pode colocar em produção!

**Comment by leonardocsantoss** [comment]
Resolvido e em produção.
