### ISSUE TITLE
Email de Boas Vindas

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#68]
Sempre que um membro é aprovado pela rotina de aprovação, enviamos um email com um texto fixo de um template.

Temos que utilizar a partir de agora o texto da campanha que tiver o prefixo "[Boas Vindas]" no assunto.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Pode colocar em produção.

**Comment by leonardocsantoss** [comment]
Em produção.
