### ISSUE TITLE
Usuários que estão marcados com opt-out estão recebendo emails

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#69]
Confirmar que todas as rotinas de envio de email não estão considerando os Spam e Opt-out

**Comment by leonardocsantoss** [comment]
Na rotina de Campanha considera apenas os emails Ativos e Não Confirmados.

As demais rotinas não fazem distinção do status do email. São elas:

- Validação de email (Cadastro de Pessoa ou Membro)
- Validação de email (Action da tela de Pessoa)
- Seja bem vindo (Action de aprovação da tela de Membro)
- Atualização cadastral (Action na tela de Membro)
- Atualização cadastral (Form requisitando atualização do Membro)
- Enviar convite (Action na tela de Círculo)

Qual delas preciso não considerar os status Spam e Opt-out?

**Comment by josircg** [comment]
Nenhuma Leonardo. Spam e Opt-out é a indicação de que a pessoa não deve receber email em hipótese nenhuma.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by leonardocsantoss** [comment]
Em produção.
