### ISSUE TITLE
Alterar o layout do Home para mostrar em 2 colunas os artigos listados na seção Home

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#7]
Pode tomar como base o site:

http://redesustentabilidade.org.br/

**Comment by leonardocsantoss** [comment]
Resolvido. Criei a seção Home(http://teste.raiz.org.br/admin/cms/section/9/) só adicionar os artigos a ela, que vai aparecer na home. Lembrando que o que vai aparecer é a chamada.

**Comment by josircg** [comment]
Só altere a cor do botão para verde para ficar compatível com o layout.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
Algumas mudanças de layout!

1) Vamos experimentar colocar 3 colunas ao invés de 2.

2) No template que mostra o artigo, colocar uma coluna do lado direito que irá listar o Raíz Notícias.

3) No lado esquerdo, no lugar do Raíz Notícias, mostrar os artigos da seção "Princípios"

**Comment by leonardocsantoss** [comment]
Ajustado.

**Comment by josircg** [comment]
1) Aumente uns 20px a largura da primeira coluna para que a opção "Cadastro para colaborador" apareça em uma única linha.

2) Crie uma terceira seção na 1a coluna que listará os artigos das Redes Sociais. Mas ao invés de mostrar o título, mostrará a chamada.

**Comment by leonardocsantoss** [comment]
Resolvido.
