### ISSUE TITLE
Melhorias no inline dos membros dos Círculos

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#70]
1) Alguns círculos já estão com mais de 200 membros e a edição do círculo fica lenta. Temos que incluir uma paginação do inline ou então incluir um campo de busca.

2) Incluir uma coluna com o telefone do membro.

3) Incluir uma coluna para indicar se o membro é filiado.

**Comment by leonardocsantoss** [comment]
1, 2, 3) Resolvidos. Coloquei direto em produção.

**Comment by josircg** [comment]
Vc colocou o email e não o telefone na coluna nova.

**Comment by leonardocsantoss** [comment]
Foi mal! Coloquei os campos de celular e telefone. Coloquei direto em produção.

**Comment by josircg** [comment]
Mais um ajuste: não mostrar os membros que estejam marcados como opt-out.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
Permitir a inclusão de um novo membro pelo superuser ou pelo administrador do círculo. Se for facilitar, crie um novo inline.

**Comment by leonardocsantoss** [comment]
Criei um novo inline só para adicionar.
Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Esse pode colocar direto em produção.

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
Abrir um controle para que se possa fazer um filtro pelo nome e apenas pelos administradores.

**Comment by leonardocsantoss** [comment]
Adicionei no inline. Coloquei apenas no ambiente de testes.

**Comment by leonardocsantoss** [comment]
Em produção.
