### ISSUE TITLE
Novo Perfil Articulador

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#71]
1) Novo grupo Articulador.

2) Nova classe:

```
classe ColetaArticulacao(models.Model):
   UF = ForeignKey(UF)
   municipio = ForeignKey(Municipio) - Aceita Null
   zona = IntegerField() - valor máximo 9999 - aceita Null
   articulador = ForeignKey(Membro)
```   

Regras:
* Admin permitindo filtro por UF e Cidade e Search pelo Nome ou Email do articulador.

* A escolha do Articulador não pode ser feita via ComboBox.
* A escolha do município tem que trazer apenas os munícipios da UF selecionada
* Só permitir a cidade em branco caso o perfil do usuário corrente for Cadastro. 
* Caso a cidade esteja em branco, incluir o grupo Articulador ao usuário do articulador.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

**Comment by josircg** [comment]
Ficou faltando uma crítica importante: se o Perfil for Articulador, ele só poderá incluir, alterar ou excluir registros do mesmo estado do qual ele é articulador.

**Comment by leonardocsantoss** [comment]
Ajustado.
