### ISSUE TITLE
Erro na imagem do Botão Compartilhar do Facebook

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#72]
A imagem que o Facebook carrega não é a imagem do artigo.

**Comment by leonardocsantoss** [comment]
Como algumas imagens são pequenas demais, o Facebook troca elas ou outras de acordo com o conteúdo da página.

Use o Debug(https://developers.facebook.com/tools/debug/og/object/) e veja um exemplo:

Esse artigo a imagem é grande: http://www.raiz.org.br/por-uma-internet-livre-universal-e-acessivel-todos, veja que vai ficar a imagem normalmente.

Já esse artigo (http://www.raiz.org.br/teia-plenaria-6) a iamgem é pequena, ai o Facebook troca ela, e coloca uma mensagem informando isso: "Based on included and inferred properties, the below preview is what users will see when they share this URL."

**Comment by josircg** [comment]
Caso a imagem do artigo seja menor que 200x200, utilizar a imagem facebook_padrao.jpeg

**Comment by leonardocsantoss** [comment]
O tamanho padrão que melhor se ajustou foi 470x275. Adicionei a imagem pelo filebrowser com o nome facebook_padrao.png
