### ISSUE TITLE
URLs inválidas que são encontradas pelos buscadores

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#74]
Os buscadores estão tentando buscar URLs que não existem mais. 

Not Found: /grupos-de-trabalho/
Request Method:	GET
Request URL:	http://www.raiz.org.br/grupos-de-trabalho/
	
'Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)'

Como a gente pode descobrir qual a página que está fazendo referência a esse site?

**Comment by leonardocsantoss** [comment]
Eu tentei fazer essa pesquisa no google(https://www.google.com.br/?gws_rd=ssl#q=site:www.raiz.org.br+grupos-de-trabalho) mais ele não retornou nada.

Cadastra o site nas ferramentas para webmaster do google(https://www.google.com/webmasters/#?modal_active=none) vamos ter uma ideia das páginas indexadas.

**Comment by josircg** [comment]
Se vc reparar o problema ocorria só no Yahoo. Eu criei um link simbólico para que o problema não ocorra novamente.
