### ISSUE TITLE
Novo Layout

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#76]
1) Trazer a base de produção para o ambiente de teste

2) Utilizar essa cor de fundo:

http://www.raiz.org.br/media/uploads/raiz_logos_imagens/logo_fundo_branco.jpg

E no lugar do branco, usar:

http://teste.raiz.org.br/media/uploads/raiz_logos_imagens/logo_fundo_branco.jpg

3) Diminuir as margens internas da coluna da esquerda.

**Comment by leonardocsantoss** [comment]
1) Copiado, copiei a pasta de media também.

2) 3) Acho que era isso. http://teste.raiz.org.br/

**Comment by josircg** [comment]
Temos que definir alguns estilos:

- bullet: http://teste.raiz.org.br/manifesto-cidadanista
- a tag <img> do artigo é sempre com uma margem direita de 5px

**Comment by leonardocsantoss** [comment]
Ajustados... Só não entendi esse item: "a tag  do artigo é sempre com uma margem direita de 5px"

**Comment by leonardocsantoss** [comment]
Ajustado.

**Comment by josircg** [comment]
2) Os boxes da coluna tem que ser menores e temos que ficar as figuras para que fiquem todas do mesmo tamanho. Tem que diminuir também a quantidade de texto ou então deixe apenas o título.

3) O link do Twitter continua desalinhado.

4) Ok

5) Ok

**Comment by leonardocsantoss** [comment]
2) A ideia foi deixar as imagens com o tamanho máximo de 300px. Além disso, deixei o texto dos boxs apenas com 20 palavras.

3) Ajustado.

**Comment by josircg** [comment]
4) Temos que melhorar a visualização do cabeçalho para telas menores:

![captura3](https://cloud.githubusercontent.com/assets/634507/15857074/c6fd470a-2c8f-11e6-90af-66ad6b811994.png)

5) Vamos experimentar retirar o menu "Home". Para isso, a gente tem colocar um link do home no logo da Raiz.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
![ruim](https://cloud.githubusercontent.com/assets/634507/16469477/95ca69de-3e27-11e6-9899-c38d8c3b4fb5.png)

Ainda tá ruim. Porque essas margens tem que ficar tão grandes?

**Comment by leonardocsantoss** [comment]
Agora foi. Testei em várias resoluções.

**Comment by josircg** [comment]
1)  O Pesquisar ainda está muito feito abaixo do logotipo. Tente colocar ele do lado quando a tela permitir.

2) Refactoring do Login

Os usuários estão se perdendo com aqueles botões antes de pedir o login. Vamos retirar todos os elementos, inclusive os menus laterais, etc e deixar apenas o login centralizado. Veja o exemplo abaixo:

![login](https://cloud.githubusercontent.com/assets/634507/16560117/b0d49dbe-41c7-11e6-9da7-32bdb9b1a37c.png)

**Comment by leonardocsantoss** [comment]
1) Eu fixei ele no topo direito.

**Comment by leonardocsantoss** [comment]
2) Resolvido. Olha se ficou legal: http://teste.raiz.org.br/login/

**Comment by josircg** [comment]
O botão de Entrar tem que ficar do lado esquerdo senão o usuário vai se enrolar.

Vc testou também no celular e com um redirect ?

**Comment by leonardocsantoss** [comment]
Coloquei do lado esquerdo. Já testei sim tanto com o redirect quanto no mobile, tudo está ok.
