### ISSUE TITLE
Python 3, Django 1.8 e postgresql

### ISSUE THREAD

**Issue by kureck** [josircg/raizcidadanista#77]
Não seria possível atualizar o código para versões mais atuais? Além disso, não seria uma boa considerar utilizar o PostgreSQL em vez do MySQL?

**Comment by josircg** [comment]
Sobre o Django: temos intenção sim. Só não temos braços. Estamos priorizando outras demandas.
Mas se você quiser, você já pode abrir um branch para fazer a conversão.

Sobre o MySQL/PostgreSQL: como temos a intenção de utilizar o Aurora da Amazon (por conta da escalabilidade), demos preferência para usar o MySQL.

**Comment by josircg** [comment]
Tô fechando a issue pois não teve mais interação. Só estamos deixando abertas as que já são consenso. Quando vc tiver uma nova consideração, reabre por favor.
