### ISSUE TITLE
Tela principal da Teia

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#78]
Na view **/forum**

1) retirar o menu horizontal e o quadro que tem a logo + pesquisar
2) colocar o logo da Raiz BEM menor e acima do menu lateral.
2) substituir o título Fórum por Teia Digital
4) Substituir o menu lateral com as seguintes opções:

Meus grupos - irá mostrar a lista de grupos em que ele está inscritos
Não Lidos - irá mostrar os tópicos não lidos dos grupos em que ele se inscreveu
Recentes - irá mostrar as conversar mais recentes (independente das que existem inscrições)
Diretório - irá listar todos os grupos do sistema
Pesquisa - View exclusiva para pesquisa
Meu Perfil
Sair

**Comment by leonardocsantoss** [comment]
1)2)3) Resolvido.

4) Algumas dúvidas:

1. Recentes: Me dar uma ideia de como vai ficar essa listagem. Seria todos os tópicos ordenados pelos que tiveram Conversas mais recentes? Ou as Conversas vão aparecer soltas na listagem?
2. Diretório: O usuário que não está inscrito em um grupo poderá clicar no link deste grupo e ver/adicionar Tópicos e Conversas?
3. Pesquisa: Quais os modelo e campos que serão pesquisados? Grupo.nome, Topico.titulo e Conversa.texto?
4. Meu Perfil: A tela será igual a do Meu Perfil do site?

**Comment by josircg** [comment]
3) Como vc está calculando os não lidos? Não está faltando um atributo TopicoOuvinte.DtLeitura ?

4.1) Recentes: Tem que listar os tópicos dos grupos dos quais ele é ouvinte, ordenando do mais recente para o mais antigo, com paginação.

4.2) Colocar o título Teia Digital com a descrição: Lista de todos os grupos existentes na Teia Digital

4.3) A pesquisa terá 3 campo: Texto, Autor, Grupo

No texto, iremos buscar pelo Tópico.Titulo, Conversa.Texto, 
Se o Autor estiver preenchido, filtraremos pelo autor da conversa.
Se o Grupo estiver preenchido, filtraremos pelo texto apenas nos tópicos do grupo

4.4) Exatamente.

**Comment by leonardocsantoss** [comment]
3) Eu criei o TopicoUsuario para isso. Prefere colocar tudo no TopicoOuvinte?

4.1) Como é feito o cadastro do Ouvinte, ainda não temos isso.
4.2) O usuário que não está inscrito em um grupo poderá clicar no link deste grupo e ver/adicionar Tópicos e Conversas?
4.3) A ideia foi pesquisar tópicos pelos 3 campos descritos.
4.4) Resolvido.

**Comment by josircg** [comment]
4.1) TopicoOuvinte! https://github.com/josircg/raizcidadanista/blob/master/raizcidadanista/forum/models.py#L63

4.2) Sim!

**Comment by leonardocsantoss** [comment]
4.1) Fiz o merge do TopicoUsuario com o TopicoOuvinte, e usei o seguinte script para popular o TopicoOuvinte:
`
from forum.models import GrupoUsuario
for gu in GrupoUsuario.objects.all(): gu.save()
`
4.1) Terminei a tela.
4.2) Ok.

**Comment by josircg** [comment]
1) http://teste.raiz.org.br/forum/ - alterar o título para os "Teia Digital - Meus grupos"
2) Não mostrar a descrição do grupo, só o título
3) Substituir o link "Meu Perfil" pelo "Meus grupos" no cabeçalho do site. Após o login, sempre encaminhar para o fórum

**Comment by leonardocsantoss** [comment]
Resolvido.
