### ISSUE TITLE
Fonte padrão do texto tem que ser igual ao que foi definido no layout original.

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#8]
Hoje está entrando Arial 10. Tem que ser a mesma fonte do PDF com a mesma cor.

**Comment by leonardocsantoss** [comment]
Ajustado. A fonte é Arial 13, como ela ficou muito pequena eu coloquei a Arial 14.

**Comment by josircg** [comment]
Não funcionou. Veja por exemplo em: 

http://teste.raiz.org.br/carta-aos-jovens-por-luiza-erundina/

O sistema não pegou a fonte padrão.

**Comment by leonardocsantoss** [comment]
Resolvido. Era só a cor e o cache do css.
