### ISSUE TITLE
Fechamento do Tópico

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#81]
O criador ou administrador do grupo pode fechar um determinado tópico. E a partir daí, não se pode mais permitir incluir novas conversas ou curtidas nele.

O ideal é que tenhamos um método Topico.Editavel() que indique se ele pode ainda receber conversas ou não já que teremos outras condições que não permitirão que a pessoa possa postar.

1) criar um botão "Encerrar Tópico" que fique visível para o administrador do grupo e para o autor.

2) criar um botão "Reabrir Tópico" que fique visível para ambos caso a o tópico esteja fechado.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by leonardocsantoss** [comment]
O administrador estava sem "permissão" de fechar o tópico. Ajustado, coloquei direto em produção.
