### ISSUE TITLE
Limpeza das mensagens

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#82]
1) Teremos que fazer o parse das conversas cadastradas para retirar todos os 

`<font> e </font>, <div> e </div>`

O objetivo é que o usuário não tenha como colocar fontes maiores ou menores no texto.

2) Permitir colocar algumas cores pré-definidas. Como podemos fazer via CSS já que iremos retirar o <font> ?

**Comment by leonardocsantoss** [comment]
A ideia foi remover toda o estilo do texto quando o usuário copia e cola no editor, desta forma não vamos precisar fazer o parser. Além disso, adicionei o bullet e o color no editor de texto.
