### ISSUE TITLE
Implementar nuvem de hashtags

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#84]
Podemos usar o mesmo da casa do saber ou algum mais moderno:

https://www.jasondavies.com/wordcloud/

Ela pode ser anexada antes do box lateral de eventos.

Inicialmente, vamos ter uma view /calcula_tags que irá pegar as 30 palavras + utilizadas nos posts dos últimos 7 dias e gravar em um registro fixo dos Recursos.

Não considerar palavras com menos de 3 caracteres, preposições e artigos a relação abaixo: ante,  após, contra, desde, entre, para, perante, sobre, trás, conforme, consoante, segundo, durante, mediante, visto, devido, como, causa, porque, aquele, aquela, aqueles, naquele, naquela, aquilo, dele, deste, disto, aqui, daqui, despeito.

Quando estiver estável, a gente vai popular diariamente (via crontab) e incluir palavras de novos posts.

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei para calcular as tags todos os dias as 0h. No template, coloquei um lista de tags apenas mudando o font-size de acordo com o número de vezes que a tag foi encontrada.

**Comment by josircg** [comment]
Temos que ter um parâmetro só para registrar as exceções. Essa lista será variável.

**Comment by leonardocsantoss** [comment]
Criei o seguinte parâmetro: http://teste.raiz.org.br/admin/cms/recurso/5/

Veja que eu coloquei também um PowerButton para criar as tags, ele só vai aparecer nos dois Recursos das Tags.

**Comment by josircg** [comment]
Quando a rotina da nuvem dá erro, o site todo sai fora do ar. Temos que implementar um tratamento de erro para que simplesmente não mostremos a nuvem.

**Comment by leonardocsantoss** [comment]
Resolvido.
