### ISSUE TITLE
Implementar estrutura de Operação Financeira e Caixa

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#85]
1) Implementar modelagem Operação e Pagamento;

2) Cadastro de Operações para que se possa registrar o Saldo Inicial;

2) Transformar a Receita em Operação;

3) Cadastro de Período Contábil;

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei apenas no ambiente de testes.

Ps.: Não realizei testes.

**Comment by leonardocsantoss** [comment]
Adicionei o caixa. Lembrar de adicionar a permissão "Pode visualizar Caixa"

**Comment by josircg** [comment]
1) A rotina de Pagamento está dando erro.

2) A receita deve gerar um depósito. Temos que rodar o script.

3) implementar uma view /caixa/201509/ onde ele mostra o caixa de todas as contas em uma única listagem.

A lógica é a seguinte: 

1. Verificar se o Período está com Publico=True. Se não estiver indicar apenas que o Período não está disponível para consulta.

2. Somar o Saldo Inicial Calculado de todas as contas no primeiro dia do mês indicado

3. Listar todos os lançamentos de todas as contas em uma única listagem.

4. Mostrar o Saldo Final

**Comment by leonardocsantoss** [comment]
1) Resolvido;
2) Coloquei também para só aparecer esses tipos na listagem;
3) Adicionado.
4) Resolvido. Segue o script, rodei apenas no ambiente de testes:
```
from financeiro.models import Receita, Deposito


for receita in Receita.objects.all():
    if receita.dtpgto:
        if not Deposito.objects.filter(receita=receita):
            Deposito(
                receita=receita,
                conta=receita.conta,
                tipo='D',
                dt=receita.dtpgto,
                referencia='',
                valor=receita.valor,
                conferido=True,
                obs=receita.nota,
            ).save()
        else:
            Deposito.objects.filter(receita=receita).update(
                conta=receita.conta,
                tipo='D',
                dt=receita.dtpgto,
                referencia='',
                valor=receita.valor,
                obs=receita.nota,
            )
```

**Comment by josircg** [comment]
2) Tem que aparecer todos. Só não pode ter adição.

**Comment by leonardocsantoss** [comment]
Ok. Ajustado.

**Comment by josircg** [comment]
1) Na tela do Pagamento, só mostrar as despesas associadas ao fornecedor selecionado. E ao selecionar a despesa, trazer o tipo de despesa automaticamente.

5) A Transferência tem que ter a mesma regra do Radix gerando a 2a operação invertida.

**Comment by leonardocsantoss** [comment]
1) Resolvido.
5) Isso já está implementado.

**Comment by josircg** [comment]
Quando não há despesa associada, o sistema tem que trazer todos os tipos de despesas:

http://teste.raiz.org.br/admin/financeiro/pagamento/274/

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
A pessoa que fazia o cadastro dos pagamentos fez o registro errado das datas. Dessa forma, temos que inverter as datas de conciliação e da data informada no sistema. Pode incluir essa alteração direto no script que cria os depósitos.

Lembrando que temos que trocar a data antes de criar o depósito.

**Comment by leonardocsantoss** [comment]
O script ficou assim:

```
from financeiro.models import Receita, Deposito


for receita in Receita.objects.all():
    receita.dtaviso, receita.dtpgto = receita.dtpgto, receita.dtaviso
    receita.save()
    if receita.dtpgto:
        if not Deposito.objects.filter(receita=receita):
            Deposito(
                receita=receita,
                conta=receita.conta,
                tipo='D',
                dt=receita.dtpgto,
                referencia='',
                valor=receita.valor,
                conferido=True,
                obs=receita.nota,
            ).save()
        else:
            Deposito.objects.filter(receita=receita).update(
                conta=receita.conta,
                tipo='D',
                dt=receita.dtpgto,
                referencia='',
                valor=receita.valor,
                obs=receita.nota,
            )
```

Não rodei ele ainda.

**Comment by josircg** [comment]
Pode rodar no ambiente de teste!

**Comment by leonardocsantoss** [comment]
Pronto. Rodei no ambiente de testes.

**Comment by josircg** [comment]
Temos que alterar o script para fazer o swap das receitas ANTERIORES a 07/2016. Todas as que vieram depois já estão corretas.

**Comment by leonardocsantoss** [comment]
A ideia foi dividir o script em dois, fazendo o swap apenas das receitas cuja dtaviso__lt=date(day=1, month=7, year=2016).

```
from financeiro.models import Receita, Deposito
from datetime import date

# Swap da data
for receita in Receita.objects.filter(dtaviso__lt=date(day=1, month=7, year=2016)):
    receita.dtaviso, receita.dtpgto = receita.dtpgto, receita.dtaviso
    receita.save()

# Criar os Depositos
for receita in Receita.objects.all():
    if receita.dtpgto:
        if not Deposito.objects.filter(receita=receita):
            Deposito(
                receita=receita,
                conta=receita.conta,
                tipo='D',
                dt=receita.dtpgto,
                referencia='',
                valor=receita.valor,
                conferido=True,
                obs=receita.nota,
            ).save()
        else:
            Deposito.objects.filter(receita=receita).update(
                conta=receita.conta,
                tipo='D',
                dt=receita.dtpgto,
                referencia='',
                valor=receita.valor,
                obs=receita.nota,
            )
```
Só rodei o script na minha máquina.

**Comment by leonardocsantoss** [comment]
Em produção. Já rodei também o script acima.

**Comment by josircg** [comment]
1) Habilitar o campo de Referencia na Receita
2) No Caixa, ao clicar no depósito, abrir a tela da Receita
3) Caso não haja colaborador, mostrar a referência na descrição.

**Comment by leonardocsantoss** [comment]
Ajustado. Coloquei apenas no ambiente de testes.

**Comment by leonardocsantoss** [comment]
Em produção.

**Comment by josircg** [comment]
Na tela da Receita, 

1) habilitar o filtro por data hierárquico
2) Incluir a referência no grid.

**Comment by leonardocsantoss** [comment]
Ajustado. Em produção.
