### ISSUE TITLE
Rotina de Mala Direta: incluir um filtro pelo auth.user.Group

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#86]
Trazer todas as pessoas de um determinado perfil 

http://www.raiz.org.br/admin/cadastro/pessoa/mala-direta/

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei direto em produção.

**Comment by josircg** [comment]
Incluir um filtro pelo status do colaborador

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei direto em produção.
