### ISSUE TITLE
Integração com o Telegram!

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#87]
https://core.telegram.org/bots

O objetivo é enviar notificações para o bot sempre que haja conversação em um tópico do fórum.

**Comment by leonardocsantoss** [comment]
Resolvido. Eu criei o BotRaiz.
Link: https://telegram.me/raiz_bot
Token: 222913462:AAF7jAFEDDMcuBnddUltEJkDOmTCmqQ_AfY

Quando você inicia uma conversa com o bot, ele envia um link para você associar o Telegram ao usuário do Raiz. Feita a associação todas as conversas que o usuário está como Ouvinte vai chegar pelo bot.

**Comment by josircg** [comment]
As menções não estão funcionando. Por enquanto, vamos enviá-las mesmo que a pessoa não tenha marcado a opção de Sempre Receber.

**Comment by leonardocsantoss** [comment]
Blz. Retirei a lógica que verificava se ele marcou "Sempre Receber".

**Comment by josircg** [comment]
Leonardo, tem sempre que ficar atento para não colocar nenhuma senha no repositório. Esse repositório é aberto!

**Comment by josircg** [comment]
O Telegram está retornando:

http://127.0.0.1:8000/forum/grupo/3/topico/5/#conversa-99

**Comment by leonardocsantoss** [comment]
Sempre esqueço desse detalhe. Coloquei a API Key no settings/production.py apenas no ambiente de testes. 

Não tem nenhuma senha no settings.

Quanto a esse erro do Telegram retornando o http://127.0.0.1:8000/... foi porque esqueci de desabilitar do meu ambiente local. Fiz isso agora mesmo.

**Comment by josircg** [comment]
Corrigir o erro do listener que você citou no email.

**Comment by leonardocsantoss** [comment]
Resolvido.

Como o gunicorn abre mais de uma thread para o projeto, então mais de um robot estava sendo aberto. Desta forma, o usuário podia receber as mensagens duplicadas.

A ideia foi criar um management e colocar ele para ser executado no supervisord.

**Comment by josircg** [comment]
Essa rotina já foi para produção?

**Comment by leonardocsantoss** [comment]
Sim.

**Comment by josircg** [comment]
Temos que incluir um debug ou trace para entender porque alguns usuários não conseguem se registrar no bot.

**Comment by leonardocsantoss** [comment]
Adicionei um log no membro quando o usuário associa a conta dele ao telegram, assim temos uma ideia de quando foi a ultima associação que deu certo.

Acrescentei também um "status" do telegram no footer do admin. O status verifica se o processo do telegram está ativo ou não.

**Comment by josircg** [comment]
Leonardo, dá uma olhada no email que eu tinha te enviado anteriormente a uns 5 dias atrás. O problema é que o usuário dá o /start e o sistema não retorna nada.

Temos que entender por que isso ocorre?

**Comment by leonardocsantoss** [comment]
Se o sistema não retornar nada é porque ele está inativo.
