### ISSUE TITLE
Controle de Notificações

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#88]
Permitir que os usuários controlem como serão feitas as notificações para eles. Eles podem se inscrever ou se desinscrever para receber notificações para um tópico ou para um grupo.

Esse controle será feito através de um botão no topo da tela nos mesmos moldes do Watch/Unwatch que temos aqui no GitHub. Nele o usuário poderá selecionar as opções: 

* Sempre receber notificações
* Resumo Diário
* Apenas notificações de votação
* Não receber notificações

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
Novo atributo em TopicoOuvinte.dtnotificacao = DateTimeField()

1) Sempre que uma conversação nova for gravada, passar a enviar email para as pessoas que pediram Sempre receber notificação SE o data atual for 1h > dtnotificacao do usuário. Caso o email seja enviado gravar em dtnotificacao

Assunto: Tópico %s atualizado no grupo %s
Clique aqui para ler o tópico <<Link para o tópico>>
Clique aqui para desabilitar essa notificação <<Link que chame view que desabilita o tópico>>

Usar esse mesmo atributo para que uma menção não seja enviada 2 vezes.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
O botão de notificações está muito grande e ocupando muito a tela. Vamos trocar por um ícone que abra o combobox. Usando por exemplo algo do tipo: https://image.shutterstock.com/display_pic_with_logo/610318/144150364/stock-vector-mail-icons-144150364.jpg

**Comment by leonardocsantoss** [comment]
Olha se tu gosta dessa ideia: http://teste.raiz.org.br/forum/grupo/1/topico/1/

**Comment by josircg** [comment]
Ficou ótimo! Só que temos que colocar o botão "Encerrar o tópico" na mesma linha.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
Pô Leonardo, não dá para colocar na mesma linha do título para ficar ainda mais conciso?

**Comment by leonardocsantoss** [comment]
Dá sim. Coloquei.
