### ISSUE TITLE
Categorização dos Tópicos

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#89]
1) Nova classe GrupoCategoria onde o administrador do grupo poderá cadastrar categorias para os tópicos em cada grupo. Terá por enquanto só um atributo com a **descrição**

O administrador poderá criar as categorias na própria tela de edição do grupo:

http://teste.raiz.org.br/forum/grupo/1/editar/

2) Novo atributo Topico.Categoria - Ele será preenchido através de um Combo que ficará habilitado para o criador do tópico (ou para o administrador do grupo). É possível deixar a categoria em branco. Caso não haja uma grupo de categorias para o grupo, não mostrar o combo. 

3) Habilitar um combo na tela que mostra os tópicos do Grupo para que o usuário possa filtrar as mensagens de uma categoria específica. Se o usuário for administrador do grupo, mostrar também um botão "Edição" ao lado do combo da categoria que irá levar para o ambiente do admin por enquanto.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
A categoria não deve aparecer se não existir nenhuma opção. Você deixou como obrigatória!

http://teste.raiz.org.br/forum/grupo/4/topico/adicionar/

**Comment by leonardocsantoss** [comment]
3) Resolvido.

**Comment by josircg** [comment]
O botão de Categoria está aparecendo mesmo quando não existe nenhuma categoria:

http://teste.raiz.org.br/forum/grupo/3/

**Comment by leonardocsantoss** [comment]
Resolvido.
