### ISSUE TITLE
Gerenciamento das Imagens

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#9]
1) Dá para remover do editor HTML a opção de fazer Upload de Imagens por lá ? Os usuários se perdem muito com isso.

2) No FileBrowser, criar uma função para mover um arquivo para outra pasta.

3) Ainda no FileBrowser, não está sendo possível excluir um arquivo ou pasta.

**Comment by leonardocsantoss** [comment]
1) Não consegui remover.

2) Para mover clica em editar o arquivo, ai vai ter agora nas "Ações" a ação Mover.

3) Coloquei um link para excluir direto na listagem. Mais é possível também ver esse link clicando em editar.

**Comment by josircg** [comment]
Tenta remover a div da aba upload atraves de javascript.

**Comment by leonardocsantoss** [comment]
Fiz diversos ajustes no ckeditor. Acredito ter conseguido remover todos os erros dele. Dessa forma, não será mais necessário retirar o botão de upload.

**Comment by josircg** [comment]
1) Pode deixar o upload então.
4) Faltou apenas permitir selecionar as pastas. Hoje ele mostra tudo junto.

**Comment by leonardocsantoss** [comment]
Resolvido. A ideia foi usar esse projeto: http://demo.tutorialzine.com/2014/09/cute-file-browser-jquery-ajax-php/

**Comment by josircg** [comment]
O File Upload não está funcionando em determinados navegadores. Eu tentei no Linux e no Windows e não consegui reproduzir. Ele vai até o final e depois da "Failed". Me lembro que esse problema também ocorreu na FGV e depois você consertou. Será que não é problema de permissão ?

**Comment by leonardocsantoss** [comment]
Implementei esse plugin.

https://github.com/blueimp/jQuery-File-Upload/

Ele usa html5, e eu deixei com o mesmo css anterior. Mudou pouca coisa.

**Comment by josircg** [comment]
As imagens estão sendo gravadas sem permissão de leitura e quando o usuário tenta acessar, dá Forbiden.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
Leonardo, o problema voltou a acontecer. O erro acontece quando eu faço o upload pelo ck_editor

**Comment by leonardocsantoss** [comment]
Coloquei um chmod 664 após o upload do arquivo. Espero ter resolvido o problema.
