### ISSUE TITLE
Diretório e Categorização dos Grupos

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#90]
2 novos atributos no grupo:
- Localização: char(1): para indicar se ele é Nacional, Estadual ou Municipal
- Temático: boolean: para indicar se ele é Temático

Na tela de Diretório, habilitar 3 filtros: um pelo nome do grupo, um para a Localização e uma para indicar os temáticos.

http://teste.raiz.org.br/forum/diretorio/

**Comment by leonardocsantoss** [comment]
Resolvido. Está apenas no ambiente de testes.

**Comment by josircg** [comment]
1) Faltou incluir os 2 atributos no admin
2) Na listagem dos diretórios mostrar com paginação.
3) Na edição do admin, deixar o inline readonline.

**Comment by leonardocsantoss** [comment]
1) Tinha incluído na classe errada. :(
2) Já está. A paginação está de 10 em 10.
3) Ajustado.

**Comment by josircg** [comment]
http://teste.raiz.org.br/forum/diretorio/

1) Na listagem do diretório só mostrar a primeira linha da descrição do grupo.

2) Mostrar também se o grupo é Nacional, Estadual ou Municipal e se é Temático.

3) Mostrar também a quantidade de usuários inscritos e a data de última atualização.

**Comment by leonardocsantoss** [comment]
Ajustado.
