### ISSUE TITLE
Novos controles no Editor HTML das conversações

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#91]
1) Permitir incluir links.

2) Tem algum controle já pronto para incluir emoticons no editor de html que estamos usando ?

**Comment by leonardocsantoss** [comment]
1) Adicionado;
2) Tem sim, adicionei também.

**Comment by josircg** [comment]
Permitir a inclusão de Imagens e arquivos. Gravar sempre o nome do arquivo como UUID mas não dar a opção de escolher o diretório.

Se for imagem, mostrar no corpo do timeline (como se fosse uma conversação) 
Se for arquivo, mostrar a referência para que as pessoas possam fazer download e o autor possa excluir o arquivo.

**Comment by leonardocsantoss** [comment]
Resolvido. Usei o campo Conversa.arquivo que já existia.

**Comment by josircg** [comment]
Tentei adicionar uma imagem e deu erro:

Request Method:	POST
Request URL:	http://teste.raiz.org.br/forum/grupo/3/topico/5/
Django Version:	1.4.22
Exception Type:	IOError
Exception Value:	
[Errno 2] No such file or directory: u'/var/webapp/raizcidadanista-teste/raizcidadanista/raizcidadanista/media/forum/5017ea5e-9854-4aba-965d-2b33fd315234.jpg'

**Comment by leonardocsantoss** [comment]
Resolvido!
Ex.: http://teste.raiz.org.br/forum/grupo/3/topico/5/

**Comment by josircg** [comment]
1) Colocar os botões ao lado do adicionar
2) tem que deixar um mouse-over com cor diferente para que o usuário entenda que ele pode clicar no botão.
3) Aproveite e diminua em 2px as margens dos boxes.

**Comment by leonardocsantoss** [comment]
Ajustado. Não coloquei o botão de "Arquivo" ao lado, quando é uma edição, pois neste caso, temos um checkbox de limpar o arquivo.
