### ISSUE TITLE
Prestação de Contas

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#93]
Implementar uma view /caixa/201509/ onde ele mostra o caixa de todas as contas em uma única listagem.

O primeiro passo é verificar se o Período está com Publico=True. Se não estiver indicar apenas que o Período não está disponível para consulta.

Caso positivo, a view retornará um grid e um gráfico lateral. O grid retornará as seguintes linhas:

Saldo Inicial:
Total de Receitas:
Despesas Agrupadas por Tipo de Despesa:
Saldo Final:

O gráfico lateral mostrará um pie chart com os tipos de despesas totalizadas:

<Detalhamento> que chamará a view /caixa_detalhe/201509/

A view /caixa_detalhe/ irá mostrar um grid com as seguintes linhas:
1. Saldo Inicial: Somar o saldo inicial de todas as contas no primeiro dia do mês indicado.
2. Listar todos os lançamentos de todas as contas em uma única listagem listando na descrição
3. Mostrar o Saldo Final

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei um PowerButton no Período Contábil só para saber qual é a url. Ele só aparece se o Período for público.

Ex.: http://teste.raiz.org.br/financeiro/caixa/201509/

**Comment by josircg** [comment]
Ficou excelente. Faltou apenas colocar os números com separador de milhar.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
Quando o pagamento tiver arquivo anexado, tem que habilitar um link para que o arquivo seja aberto.

**Comment by leonardocsantoss** [comment]
Resolvido.

Acabei descobrindo esse problema: Esta [Operação](http://teste.raiz.org.br/admin/financeiro/operacao/2/), que é do tipo "Deposito à vista", não tem Depósito associado. Nestes casos, como devo fazer?

**Comment by josircg** [comment]
Vc apagou a operação e eu tenho como ver o problema. 

Mas a lógica é uma só: vc tem sempre que se basear na Operação para mostrar os saldos. Caso o objeto associado não exista, vc deve indicar de alguma forma para que o usuário possa agir.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
http://www.raiz.org.br/financeiro/caixa/201606/

1) Incluir uma linha de Rendimentos Financeiros que deverá conter as operações do mesmo tipo;
2) Incluir uma linha de Outras Receitas que serão as receitas sem colaborador identificado;
3) Incluir uma linha com o Total das Despesas;
4) Não mostrar as linhas que tem valor zero;

**Comment by leonardocsantoss** [comment]
Resolvido. Coloquei direto em produção.
