### ISSUE TITLE
Busca de Articuladores

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#95]
Nova página de busca de Articuladores onde a pessoa entra com a cidade ou UF e o sistema mostra os dados do articulador.

Tem que ser bem similar ao que já temos dos círculos só que a a busca deve ter uma lógica especial: caso não exista um articulador na cidade, mostrar o articulador do Estado. Caso não exista o do Estado, mostrar os Articuladores Nacionais.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by leonardocsantoss** [comment]
Coloquei na seguinte url: http://teste.raiz.org.br/articuladores/

**Comment by josircg** [comment]
O Estado tem que ser obrigatório pois existem cidades com o mesmo nome em estados diferentes.

Depois pode colocar em produção.
