### ISSUE TITLE
Listagem dos Tópicos

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#96]
1) Na listagem dos Tópicos Recentes e na Listagem dos tópicos de um grupo, indicar ao lado do autor:

* discussão iniciada em:
* quantidade de comentários
* quantidade de pessoas envolvidas na discussão

2) Na listagem de Não Lidos, utilizar o mesmo layout que descreve o grupo que existe na listagem de Diretórios

**Comment by leonardocsantoss** [comment]
Resolvido.
