### ISSUE TITLE
Pesquisa do Fórum

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#97]
A pesquisa tem 3 campo: Texto, Autor, Grupo

No texto, iremos buscar pelo Tópico.Titulo, Conversa.Texto, 
Se o Autor estiver preenchido, filtraremos pelo autor da conversa.
Se o Grupo estiver preenchido, filtraremos pelo texto apenas nos tópicos do grupo

Incluir um checkbox box "Listar conversas" com a opção desmarcada. Se ela for marcada, deve-se listar as conversas que tem o texto e não os tópicos.

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
1) O cheque box Listar conversar ficou bagunçado na tela.

2) O botão de Próximo da pesquisa está com um link errado. Dá erro.

**Comment by leonardocsantoss** [comment]
Resolvido.
