### ISSUE TITLE
Adicionar Novo Tópico / Ouvinte

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#98]
Hoje quando a pessoa não está registrada em um grupo, o sistema emite apenas um erro dizendo que a pessoa não tem permissão de incluir novo tópico. Temos que corrigir isso:

1) Novo atributo: Grupo.privado: boolean('Somente membros autorizados', default=False). Na edição do grupo, permitir a edição do campo.

2) Se o atributo for True, tem sempre que permitir a inclusão do novos tópicos por qualquer colaborador. Caso contrário, informar:

Este grupo é privado e só permite a inclusão de novos tópicos pelos membros previamente aprovados. Clique no botão abaixo para solicitar o seu ingresso nesse grupo.

Enviar email para os jardineiros do grupo com um link para view /grupo_aprovar_usuario?userid=999&groupid=999  que já adicione o usuário automaticamente. 

A view irá incluir o usuário no grupo passado como parâmetro.
A view deve verificar se o current user é jardineiro do grupo em questão. 
Notificar o jardineiro que o usuário foi adicionado com sucesso

**Comment by leonardocsantoss** [comment]
Resolvido.

**Comment by josircg** [comment]
Tentei adicionar um tópico e deu erro:

/var/webapp/raizcidadanista-teste/raizcidadanista/raizcidadanista/forum/views.py in get_context_data

            context['ouvinte'] = TopicoOuvinte.objects.filter(topico=self.object, ouvinte=self.request.user).latest('pk')

**Comment by leonardocsantoss** [comment]
Resolvido.
