### ISSUE TITLE
Planejamento Orçamentário

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#99]
1) Permite registrar o orçamento anual através da classe Orcamento

Já criei a estrutura e o admin básico. Falta implementar algumas regras:

* Na tela de edição, habilitar um campo "Repetir até o mês". Nesse caso, após o save(), gravar novos orçamentos marcando o orcamento_pai.
* Sempre que houver edição de um orçamento, verificar se ele tem filhos. Nesse caso, deve-se perguntar se os orçamentos filhos também devem ser atualizados.

2) Visualização do Planejamento Orçamentário Anual

Lista os orçamentos agrupados onde cada coluna é um mês e os tipos de despesa vem em cada linha. Seguir o modelo em anexo:

https://docs.google.com/spreadsheets/d/1tDq7DetjZ1xy2jQ0e5ufXvH5lxUTIDEMi1Q-AGfLOtQ/edit?ts=56309da2#gid=2024584460

Ao invés de mostrar em um PDF, mostrar inicialmente em formato visual.

**Comment by leonardocsantoss** [comment]
Em andamento...

**Comment by leonardocsantoss** [comment]
1) ok.
2) Vi aqui que no exemplo tem, saldo inicial, uma linha contabilizando o total de receitas, uma com o total de despesas, e outra com o total geral. No entanto, fiz o relatório apenas com o Orçamento. Ex.: http://teste.raiz.org.br/financeiro/planejamento-orcamentario/

**Comment by josircg** [comment]
1) O Período FInal já era pra ser o campo "Repetir até o mês" :(
2) No relatório, tem que mostrar 05/2015 (se você usar apenas o periodo, ele já traz formatado)

**Comment by leonardocsantoss** [comment]
Ajustado.

**Comment by josircg** [comment]
1) O Edit só deve aparecer se o usuário estiver logado e for do Financeiro.

2) Permitir a construção:

http://teste.raiz.org.br/financeiro/planejamento-orcamentario/2016/

3) Para cada tipo de despesa, incluir uma segunda linha que mostre o valor realizado.

4) Ao final, mostrar o total geral somando todos os tipos de despesas, também com 2 colunas.

**Comment by leonardocsantoss** [comment]
1) Quando não é Financeiro deixei tudo readonly;
2) Resolvido;
3) Resolvido.

**Comment by josircg** [comment]
1) Ok
2) Ok
3) Não funcionou. Não aparece a linha com o saldo. A linha de saldo não está aparecendo.

http://teste.raiz.org.br/financeiro/planejamento-orcamentario/2015/

Tem que aparecer umas coluna para cada mês, igual ao que temos na linha do orçamento.

4) Idem.

**Comment by leonardocsantoss** [comment]
Ajustado.

**Comment by josircg** [comment]
1) Quando for R$ 0, mostrar apenas o sinal de "-"
3) O hint não está aparecendo quando eu posiciono o cursor sobre o -1000,00. E quando o usuário estiver logado, colocar um link para a tela de pagamentos. 
5) Na linha do título, coloque Orçamento x Realizado
6) Na linha do Saldo, o texto "Saldo" tem que ficar alinhado pela direita para compor melhor a tela.

**Comment by leonardocsantoss** [comment]
Resolvido.
